### ISSUE TITLE
Channel-Client should not expect an immediate response for API calls

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1049]
Currently `Channel-Client` expects a response immediately for any API call it makes. However the `xstate-wallet` sends a response after a user has confirmed it in the UI. This currently causes the channel-client to time out.

**Comment by snario** [comment]
What are our options for handling this?

**Comment by lalexgap** [comment]
> What are our options for handling this?

I think we need to remove the timeout logic from `channel-client`. That does mean that you may receive a promise from the `channel-client` that doesn't resolve for a while. (which means it may be hard to detect if the wallet isn't responding or is just waiting on the user)

The other option is changing the `channel-client` interface a bit so that it's similar to how the API works. You call `createChannel` which returns immediately and sometime later a `ChannelCreated` event is fired by the `channel-client` which the app listens for.
