### ISSUE TITLE
Upgrade openzeppelin packages to stable versions

### ISSUE THREAD

**Issue by junjizhi** [statechannels/monorepo#1055]
This [PR](https://github.com/statechannels/monorepo/pull/1052) uses beta because they were the only packages compatible with solidity 0.6. 

Once `openzeppelin` releases the stable packages, we should upgrade. The packages include 

```
@openzeppelin/contracts
@openzeppelin-solidity
```

**Comment by snario** [comment]
Did this here but hit an issue: https://github.com/statechannels/monorepo/pull/1510

Might be ready now. @geoknee maybe try if we're releasing nitro protocol docs?
