### ISSUE TITLE
Properly display progress in xstate-wallet UI

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1077]
Currently the progress returned by `getApplicationOpenProgress` is incredibly basic and doesn't give the user meaningful information. We should give a more accurate number based on the state of sub-protocols.

**Comment by andrewgordstewart** [comment]
Do we even care about displaying progress? It doesn't seem like something we want in web3torrent, which would be creating many app channels, possibly concurrently.

**Comment by lalexgap** [comment]
> Do we even care about displaying progress? It doesn't seem like something we want in web3torrent, which would be creating many app channels, possibly concurrently.

That's a good point, this should be deferred. I'll close this and we can reopen if necessary.
