### ISSUE TITLE
2. Check if line 196 `web3torrent-lib.ts` wire->channel mapping is fine (messaging works with multiple channels)

### ISSUE THREAD

**Issue by junjizhi** [statechannels/monorepo#1089]
https://statechannels.slack.com/archives/CMJFENMEX/p1583255145001600

**Comment by geoknee** [comment]
Just wanted to add some context which might help here: 

- I guess this is no longer L196.
- You might be partially blocked on #1085 if trying to get multiple simultaneous channels going
- the current plan is to try and get `wire` and `channel` to be 1-1. According to @spersico , there's a reasonable chance that a `wire` might get dropped and a new one created, while the `channel` is probably going to persist in that scenario. That might mean eventually we have many wires (in series) for one channel, but we should see how far we can get without doing that for now.
- `localStorage.debug = 'web3torrent:*'` is invaluable for debugging / understanding what is happening
- you can inspect the `channelCache` as a `prop` of the top level component by using React devtools

I *think* it works fine with serial channels: if you seed from tab 1, leech from tab 2 and *then* leech from tab 3, you'll see messages going to the right place.

**Comment by junjizhi** [comment]
>  A basic approach that I took (in my last PR), was to save each channelId, accountID and outcomeAddress in the wire. And each prop is set at different times.

For our reference, here's that PR: https://github.com/statechannels/monorepo/pull/1076

**Comment by junjizhi** [comment]
> When a Leecher makes a request, the Seeder creates the channel, sets the pseChannelId, and sends it as an argument in the STOP event (that you can see in the diagram that I made). The leecher, upon receiving that event, saves that argument as peerChannelId.

I could see this logic is happening here: https://github.com/statechannels/monorepo/blob/master/packages/web3torrent/src/library/web3torrent-lib.ts#L269-L276

> This goes both ways, if the Seeder starts making requests for pieces of files (becoming a Leecher), the leecher becomes a Seeder, makes another channel, set its own pseChannelId , and sends it as an argument in the STOP event

In our current UI , a Seeder can only make a new download request from an existing Leecher. Right?

One rare use case I can think of is Seeder accidentally deletes the original file and needs to fetch a copy from its Leecher.

**Comment by spersico** [comment]
> I could see this logic is happening here: https://github.com/statechannels/monorepo/blob/master/packages/web3torrent/src/library/web3torrent-lib.ts#L269-L276

Exactly
> In our current UI , a Seeder can only make a new download request from an existing Leecher. Right?

Whaat? You mean a Leecher can only make download requests from an existing Seeder? If it's that, then yes.

The thing is, the BitTorrent protocol (from which all of this is based) is made to handle all kinds of sizes of files. When you have bigger files, the possibility of having 2 or more leechers at the same time is bigger, and if one leecher has a part of a file that another leecher doesn't, there's a high chance that the second will treat the first as a seed, and ask for that part of a file, instead of the original seeder. And maybe at some point, the role might be reversed. 

Because BitTorrent tries to "balance the load" between all peers, it will try to reduce the load of the original seeder when possible.

**Comment by junjizhi** [comment]
> if one leecher has a part of a file that another leecher doesn't, there's a high chance that the second will treat the first as a seed, and ask for that part of a file, instead of the original seeder.

👍 Good explanation. With payment channels, it provides incentives to be early seeders.

**Comment by geoknee** [comment]
> When a Leecher makes a request, the Seeder creates the channel, sets the **pseChannelId**, and sends it as an argument in the STOP event (that you can see in the diagram that I made). The leecher, upon receiving that event, saves that argument as **peerChannelId**.

I just want to underline that this approach is really establishing that we can have up to *2* channels per wire, one "owned" & created by each peer if they are seeding to the other.

**Comment by junjizhi** [comment]
I played with the app locally and had a 2-leecher-1-seeder setup. I confirm that each time a wire is connected, a new channel is created. In that sense, it is 1-to-1. 

I wasn't able to trick the leecher to reuse an existing wire / channel, at least not through the UI. 

Since this doesn't impact our use scenario and this is an investigation issue, I will move on to other issues.
