### ISSUE TITLE
4. Find way to make “funds” variable less confusing / easy to mistake for the actual channel payments (in the code)

### ISSUE THREAD

**Issue by junjizhi** [statechannels/monorepo#1090]
https://statechannels.slack.com/archives/CMJFENMEX/p1583255145001600

**Comment by geoknee** [comment]
This variable is now named `buffer`. It goes up when a payment comes in, it goes down when some data goes out.  I think it will not be confused with payments any more. 

Of course, there may be some other buffers kicking around which may cause confusion, although I did not see these in the file in question or nearby. If anyone (@spersico ?) sees a problem there, or has an idea for an even better name they may reopen this issue.
