### ISSUE TITLE
8. Minimize potential confusion between term `ChannelClient` and `this.channelClient` in `web3torrent-lib.ts`

### ISSUE THREAD

**Issue by junjizhi** [statechannels/monorepo#1094]
https://statechannels.slack.com/archives/CMJFENMEX/p1583255145001600

**Comment by geoknee** [comment]
It was updated to `this.paymentChannelClient`. It is an instance of the `PaymentChannelClient`class, which I think is a standard pattern. I don't think this is an issue in fact, but @snario please reopen if you disagree.
