### ISSUE TITLE
10. Rename `createChannel` to `createPaymentChannel`

### ISSUE THREAD

**Issue by junjizhi** [statechannels/monorepo#1095]
https://statechannels.slack.com/archives/CMJFENMEX/p1583255145001600

**Comment by geoknee** [comment]
I think it's debatable if we need this now, since we already have 

```
this.paymentChannelClient.createChannel()
```

and 

```
this.paymentChannelClient.createPaymentChannel()
```

is probably only marginally better. But I'll leave it open in case someone wants to do it.
