### ISSUE TITLE
[TTT] Inject TTT Contract Address into Ember App similar to start.js in RPS

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1123]
**Problem description :confused:**
Tic Tac Toe can be run either locally or in production. Locally it should use local environment variables and in production there should be a fixed set of variables as well.

**Describe the solution you'd like :rocket:**
We need to inject at build time some variables:
* Wallet URL
* TTT Contract Address
* Anything else?

**Describe alternatives you've considered**
Inject these variables during build time similar to start.js in RPS.

**Comment by snario** [comment]
@Alonski is this done?

**Comment by Alonski** [comment]
@snario I guess. It currently works but isn't super robust.

**Comment by snario** [comment]
What do you mean robust?
