### ISSUE TITLE
1. Investigate turning off all network connections for debug UI

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1128]
**Problem description :confused:**
It would also be nice to be able to show webTorrent and stateChannels stopping and resuming downloads from each seeder.

**Describe the solution you'd like :rocket:**
We should research a way for Leechers to stop leeching from a seeder.

**Comment by geoknee** [comment]
Little more context: this would be a nice feature to have because it will allow advanced/interested users to simulate going offline. That way, we can show off the feature (not yet implemented), that their peers can challenge / forceMove them in order to recover their funds.

**Comment by geoknee** [comment]
This is a low priority for now.
