### ISSUE TITLE
3. Notify in UI if peer hasn’t sent any messages recently

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1130]
**Describe the solution you'd like :rocket:**
The idea is to show some kind of UI feedback if a seeder or leecher hasn't sent any messages for a while.

**Describe alternatives you've considered**
There was talk of doing a sand clock in the list of peers:
> Add “timeout”/ “hourglass” UI to an unresponsive peer in the channel list (how long since the last reply)

**Comment by geoknee** [comment]
Discussed today: if a wire is dropped, show a [ Challenge Channel ] button *instead* of [ Close Channel ] button.

**Comment by geoknee** [comment]
(and `onClick`, maker the `challengeChannel()` API call)
