### ISSUE TITLE
4. Hook up “close” button from ui to wallet API call. 

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1131]
**Problem description :confused:**
Right now there's a button _Close_ in the list of peers, we should integrate that to an actual function.

The leecher can also do this automatically if the torrent emits an event called DONE:
https://github.com/statechannels/monorepo/blob/master/packages/web3torrent/src/library/web3torrent-lib.ts#L319

**Comment by geoknee** [comment]
Closed via #1116
