### ISSUE TITLE
5. Figure out where to place approveBudgetAndFund() call

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1132]

**Comment by geoknee** [comment]
I suggest these calls go at the very edges of the current whimsical diagram (i.e. right before USER CLICKS START DOWNLOAD and right before USER SELECTS FILE TO UPLOAD). We don't let the user progress unless the API call resolves successfully. We allow the wallet to handle all of the UI around budgets, explaining the ledger connection to the hub, and so on. 

Once this connection has been successfully set up, when we later call `createChannel` etc (`n` times), the wallet will be able to virtual fund these channels,.
