### ISSUE TITLE
7. Messaging with Hub

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1134]
**Problem description :confused:**
We need to prepare for the communication that will be needed from web3torrent to the hub, through PaymentChannelClient.

**Describe the solution you'd like :rocket:**
It will probably be an HTTP request of some sort

**Comment by kerzhner** [comment]
Decision from a standup conversation on Monday 3/9/20 was to keep using Firebase to communicate with the hub.

**Comment by geoknee** [comment]
We can reuse our existing firebase instance (currently named `rock-paper-scissors-dev`) for this, multiplexing with some namespacing / prefixing .
