### ISSUE TITLE
9. Replace channelCache with getState

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1136]
**Problem description :confused:**
In [channel-list.tsx](https://github.com/statechannels/monorepo/blob/aa3b5f64a2025d0859bb0df6e62aa8ac105f6acc/packages/web3torrent/src/components/channel-list/ChannelList.tsx#L19)

**Comment by geoknee** [comment]
I'm no longer sure if we want to do this: we'll need to cache this data anyway for the current UI (i.e. `ChannelsList` component), and the current solution should be among the most performant (IMO).
