### ISSUE TITLE
Git: Can we do squash merge?

### ISSUE THREAD

**Issue by junjizhi** [statechannels/monorepo#1139]
**Problem description :confused:**
When I have questions about a line of code, I often go to the commit that introduces that line and its PR where I could see the set of changes.

Our current git history looks like the screenshot below. There are many small, granular commits. It's often not useful to look at one individual commit on its own. With the rainbow lines, it's hard to trace it back to the original PR.

![image](https://user-images.githubusercontent.com/2715151/76142862-bb4fd980-603f-11ea-98bd-6c864b79a0a8.png)

**Describe the solution you'd like :rocket:**

I propose we do the following in our branch:
- (For deployer / merger) Always use `Squash Merge` button when merging into master (so that it creates one commit and we can easily trace to the PR)
- (Optional) Groom the commits in your PR  before merge (e.g., squash small ones)
- (Optional) Use `git rebase` instead of `git merge` in your local branch.

The last two items are optional because it may break people's workflow and introduce too much overhead. 

I'm happy if we have squashed commits in master.

**Additional context**
For comparison, I looked at other open source repos, e.g., [openzeppelin-contracts](https://github.com/OpenZeppelin/openzeppelin-contractsl):

![image](https://user-images.githubusercontent.com/2715151/76143060-cd327c00-6041-11ea-9def-75ca62262e46.png)

The history looks cleaner and easier to navigate.

**Comment by snario** [comment]
To follow up on this I'd prefer if we were consistent with this too, but we've had this discussion before and it seems to be case by case.

My commits tends to be erratic so I like to squash them. Andrew and Mike however are better at having clean and isolated git commits where they make sense to go in on their own.
