### ISSUE TITLE
If I close a channel manually, stop sending requests 

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1159]
We should also address the complementary issue, where if I close a channel manually (or my peer does) I should then stop sending requests (because now I am choked forever,

_Originally posted by @geoknee in https://github.com/statechannels/monorepo/pull/1150#issuecomment-596610546_

**Comment by junjizhi** [comment]
@geoknee Since we [remove the close button](https://github.com/statechannels/monorepo/issues/1216), this may not be an issue any more.

**Comment by geoknee** [comment]
Agreed, the logic is somewhat inverted from what I had imagined when making this issue. Channels should not be closed manually any more.
