### ISSUE TITLE
Decouple wire choking and sending STOP

### ISSUE THREAD

**Issue by junjizhi** [statechannels/monorepo#1178]
**Describe the bug :bug:**
web3torrent currently has a behaviour that allows a little free leeching when leecher is joining the channel.  

See discussions in: https://github.com/statechannels/monorepo/pull/1163#discussion_r391046090

**To Reproduce**
1. Start seeder and leecher in two windows
2. Turn on dev console and filter web3torrent log only
3. See the behaviour described in this [comment](https://github.com/statechannels/monorepo/pull/1163#discussion_r390678890)

**Expected behavior**
Leecher shouldn't be able to start leeching before it makes the payment.

**Additional context**

**Comment by geoknee** [comment]
Let us all make sure to improve our documentation around this (e.g. whimsical diagram).

I think some notes would also be useful, describing overall philosophy of integrating channels into webtorrent.
