### ISSUE TITLE
Test opening multiple channels with the wallet.

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1185]
Web3torrent would normally want to create-and-fund multiple app channels concurrently. We should test this behaviour.

**Comment by andrewgordstewart** [comment]
I think the wallet wouldn't work properly right now, since it would involve concurrent updates to a single ledger channel.

**Comment by junjizhi** [comment]
For reference, I added multiple channel tests for the channel-client in this PR: https://github.com/statechannels/monorepo/pull/1222

**Comment by andrewgordstewart** [comment]
Here's a reasonably involved scenario: https://github.com/statechannels/monorepo/pull/1441/commits/5b2dd9c0f56a8ae83d5e62fb27199efa31f20360

I ran it a couple of times: it seems like things generally work, but one time one of the browsers got stuck closing a channel.

**Comment by andrewgordstewart** [comment]
Closing this as the test now exists in `master`. We can use another issue to track getting that test to pass 😄
