### ISSUE TITLE
[ttt] Ganache started inside build script

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1204]
`yarn prepare` triggers the build script, which triggers ganache + contract deployment:

https://github.com/statechannels/monorepo/blob/a9d546f2d700ef162da4a6095ed9c2c059fad79f/packages/tic-tac-toe/ember-cli-build.js#L7-L19

In our other packages, deploying contracts is decoupled from building the app, so that we can do that on `yarn start` but not on `yarn build`. I suggest we adopt that pattern here, too. It should save a bit of time on our circle pipeline, too.

**Comment by Alonski** [comment]
@geoknee I saw that this is how it is done in RPS in start.js. This is causing issues?

Locally shouldn't this do nothing as the contracts are already deployed?

**Comment by geoknee** [comment]
I think we want to start ganache on `yarn start` because we are also firing up a dev server, but not in `yarn build` because that is building a static site for deployment (or as a step in preparing the monorepo, in case some other package were to depend on this one).

Building the app shouldn't require ganache to be running.

This whole issue arose when I spotted ganache running when we do a top level `yarn prepare`.

**Comment by Alonski** [comment]
I could only run this when building for development which is what happens during `yarn start`

**Comment by geoknee** [comment]
Yeah I think that's what we want :+1:
