### ISSUE TITLE
Integrate Web3torrent/xstate-wallet/hub

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1211]
Work on getting all the various components working together.

**Comment by andrewgordstewart** [comment]
I am no longer working on this, as I am unsure of what work needs to be done. I believe @geoknee has been working on this, though?

**Comment by geoknee** [comment]
My initial goal is to just integrate web3torrent and x-state wallet without the hub #1135 (i.e. using direct funding). Once that works, we can get the third component working too (i.e. use virtual funding).

**Comment by lalexgap** [comment]
Closing as this is now captured in other issues.
