### ISSUE TITLE
[web3t] Handle dropped wires

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1215]
A wire is the means of communication between peers. It seems that a wire gets dropped some time after a period of no requests. This has at least two consequences: 

1. We lose uploaded/downloaded information
<img width="677" alt="Screenshot 2020-03-14 at 06 50 22" src="https://user-images.githubusercontent.com/1833419/76676904-16de1200-65c0-11ea-9d33-f3f10c22b7a2.png">

2. __We lose the ability to collaboratively close a payment channel__

(1) can be solved by maintaining a bit of state inside the relevant components. (2) is more serious, and might require that we 

(i) just go to chain in that scenario :-(
(ii) fire up a new wire and use that to do the relevant mesage passing
(iii) never let the wire drop in the first place

(iii) would seem to be by far the simplest solution, and would also solve (1) as a side effect.

**Comment by junjizhi** [comment]
When a wire is dropped, can we still rely on channel cache to close the channel? Like the first row in your screenshot?

**Comment by andrewgordstewart** [comment]
Can we just ask the wallet to conclude the channel when the wire is dropped?

**Comment by geoknee** [comment]
The problem is that by that point, the messaging system is broken, and it wouldn't be straightforward to setup a new one. If we ask to conclude when the money runs out, or when the torrent is finished, we should hopefully sneak in the conclude before the wire disappears.

**Comment by geoknee** [comment]
Of course we could use firebase as a failsafe messaging system...

**Comment by geoknee** [comment]
@spersico would increasing this timeout to something very large prevent the wire from being dropped at all? 
https://github.com/statechannels/monorepo/blob/a07292f95cd6734854bd67eef1caee8e6a2172e2/packages/web3torrent/src/library/web3torrent-lib.ts#L212

If so, would there be any adverse consequences?

**Comment by geoknee** [comment]
To reproduce a wire being dropped, I usually upload a large file >10MB, and wait for the leecher to run out of funds. And wait an additional minute or so. Then you should see NOWIRE in the Channel List UI.

**Comment by spersico** [comment]
@geoknee sorry for the late response. I'll check this out.

**Comment by junjizhi** [comment]
Based on what I've seen so far, dropped wires happen in two scenarios
a) leecher runs out of fund (https://github.com/statechannels/monorepo/issues/1216)
b) leecher cancels the download (https://github.com/statechannels/monorepo/issues/1230)
c) seeder blacklists a leecher and cancels the download (not supported yet)

For a), with https://github.com/statechannels/monorepo/pull/1236 merged, we actually want the wire to drop after timeout. Otherwise, if the channel is closed and the wire is kept indefinitely, that would be a waste. 

For b), we could drop the wire when leecher presses the cancel button.

> (1) can be solved by maintaining a bit of state inside the relevant components.

I will go with this approach to keep the download / upload info.

What do you think? @geoknee

**Comment by geoknee** [comment]
> For b), we could drop the wire when leecher presses the cancel button.

I think so, but only after we have closed all the channels on a wire. Remember that we might have 2 channels (one in each direction) on a wire; if one peer cancels the download but not the other, we still need the wire. 

And the overarching thing to keep in mind is, we need the wire if there are open channels associated with it. So we should always check that before dropping the wire.

**Comment by junjizhi** [comment]
> Remember that we might have 2 channels (one in each direction) on a wire; if one peer cancels the download but not the other, we still need the wire.

Based on the discussion on https://github.com/statechannels/monorepo/issues/1089, a wire is currently uni-directional. Looking at the `PaidStreamingExtension` class, a wire is tied to a `pseChannelId` so I'm not 1-wire-2-channels are possible. With this assumption, the logic to drop wire is simple.

Were you able to set up a wire with two channels via current UI? @geoknee
