### ISSUE TITLE
[web3t] Handle closing a channel when not my turn

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1216]
I have seen this error with the fake provider. I wanted to use this issue to kick off a discussion.

This issue should be somewhat easier to solve (than in , e.g. RPS) given we have a unidirectional payment channel. 

If it is not my turn , it should soon be as long as my counterparty is online (since the clients will be auto-responding to my updates assuming they are not malicious). (1) So the provider / wallet can just wait until it is my turn and then close the channel.

Edge cases are when the torrent is done (the channel auto closes) and  when the leecher runs out of money (**TODO: (2) leecher auto-closes the channel when they run out of funds**). 

We might decide that we do not need to offer peers the option of collaboratively closing a payment channel in any other circumstances, and (3) we can simply remove the [ Close ] button. That would be a simple way of maintaining certainty over who's turn it is when closing. 

This certainly seems preferable to (4) having the [ Close ] button disable when not my turn; that would result in a pretty flickery UI.

Clearly we must deal with the case of one party going offline, but that will require going to the chain, unless we do something fancier with sending final states across the wire.

My preference would be to definitely do (2), and then pick (3) over (1) or (4).

**Comment by junjizhi** [comment]
>  (2) leecher auto-closes the channel when they run out of funds

Will there be a use case where leecher wants to refund the channel and continue the torrenting?

**Comment by junjizhi** [comment]
> (3) we can simply remove the [ Close ] button.

Ideally this button can be hidden in a Advanced section in the UI. But if the usage is an edge and a bit confusing to users, removing it make senses to me for finishing the demo app.

**Comment by junjizhi** [comment]
The UI should probably display the channel closed reasons (at least for the leecher), e.g., 

- insufficient fund
- unexpected closing (e.g., network failure)

So the user can act on it, and so it would be more user friendly.

**Comment by geoknee** [comment]
Depending on if we decide to handle top-ups (I'm guessing probably not in the short term), we can also alert the user if they do not have enough funds to download the current file.

(That alert might never happen if files are reasonably small, bytes are priced sufficiently low, and channels have enough funds in them.)

Anyway, we might never have to close a channel for insufficient funds: because we would never open that channel. 

Unexpected closing via network failure will also involve the *challenge* flow, which we definitely want some UI for #1130 .
