### ISSUE TITLE
web3torrent: Cancel downloading doesn't work

### ISSUE THREAD

**Issue by junjizhi** [statechannels/monorepo#1230]
**Describe the bug :bug:**
Cancel and restart downloading results in errors (see the screenshot)

**To Reproduce**
- Update a large file. 
- Start download
- Leecher gets stuck
- Press cancel in leecher window
- ~~Start download again (see error)~~
Update: The crash error has been addressed in this PR: https://github.com/statechannels/monorepo/pull/1263

**Expected behavior**
Should be able to redownload

**Screenshots (if applicable)**
Leecher error screen:
![image](https://user-images.githubusercontent.com/2715151/76862482-9116cc80-6834-11ea-8b53-3cb2718f8b8f.png)

**Comment by geoknee** [comment]
This could well be related to #1215

**Comment by junjizhi** [comment]
With [this PR](https://github.com/statechannels/monorepo/pull/1263) merged, the current behaviour is, when leechers cancels the download, wire is dropped but the channel is still running. I'm working to fix it.
