### ISSUE TITLE
hub: remove hub package

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1234]
`hub` package no longer supports the `xstate-wallet`.

**Comment by kerzhner** [comment]
The [heroku hub instance](https://dashboard.heroku.com/apps/statechannels-hub-staging) can be stopped and deleted once package is removed and `rps` migrates to the `xstate-wallet`.

**Comment by snario** [comment]
(note the `hub` heroku instance is **still up** and being used for http://rps.statechannels.org)
