### ISSUE TITLE
Enhance validation of messages in/out of wallet

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1266]
We only validate Requests at the moment, using

https://github.com/statechannels/monorepo/blob/d3a53b7ecd988c50fb6d03bdee085781d6b352a6/packages/client-api-schema/src/parse-request.ts#L14-L21

We should add a `parseNotification` and `parseResponse`. and use these for *outgoing* messages from the wallet.

This might help catch current issues where messages arrive from the wallet in an unexpected format.

**Comment by snario** [comment]
We do this now:

https://github.com/statechannels/monorepo/blob/ca2d3bb4f35b9c6af0f07917b5b7dd0514efcba2/packages/xstate-wallet/src/messaging.ts#L94-L95
