### ISSUE TITLE
Leftover Budget Handling

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1270]
**Problem description :confused:**
Once a leecher downloads his desired torrent from one or more seeders, there's always a leftover buffer in the seeders.

For example, with a *BUFFER_REFILL_RATE* of 20000 wei, a *WEI_PER_BYTE* of 1 wei, and a torrent size of 62kb, with a single seeder and a single leecher, after the leecher downloads the entire file, the seeder will have 18000 wei.
That buffer should be returned somehow to the leecher.

This, I believe, is the remaining issue in order to solve inconsistent costs of torrents, of a torrent cost not being what the UI tells the leecher it is.

**Describe the solution you'd like :rocket:**
We should implement a way for the seeders to return the leftover buffer to the leecher. Maybe this could be done before closing the channel?.

**Comment by geoknee** [comment]
One issue here is that the `PaymentChannelClient` currently targets a **unidirectional** payment channel. This makes it tricky for the uploader to refund the downloader, without breaking that model.

An alternative solution might be to prevent the downloader from ever over paying. They should be able to tell that they are getting close to finishing the download, and reduce their payment accordingly such that the buffer is almost empty when the torrent finishes.
