### ISSUE TITLE
[web3t] Remove cost from magnet link

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1278]
Currently I can "hack" the app by modifying the url. It can make it display whatever I want in the UI.

Of course this doesn't change the *actual* price of the torrent: which implies we can just remove that part of the magnet link .

**Comment by junjizhi** [comment]
@geoknee 
> we can just remove that part of the magnet link .

What do you mean here? Currently we are reading the `torrent.length` value from magnet link. If we remove that part, how are we going to know the download size?

One idea is to use 
```js
torrent.on('metadata', function () {})
```
according to [webtorrent api doc](https://webtorrent.io/docs), but that's available after you connect with a peer.

**Comment by junjizhi** [comment]
If I remove the `xl=4000` params from the magnet link in the url, I got this:

![image](https://user-images.githubusercontent.com/2715151/77763946-3b9ba600-7012-11ea-9b37-b174d97a75d1.png)

And I had to refresh the seeder page. Opening the leecher link in a new window and the download hangs forever.

**Comment by geoknee** [comment]
Right... maybe we should just leave this then!
