### ISSUE TITLE
Test Torrent Capability test malfunctioning

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1311]
**Describe the bug :bug:**
I'm having issues with the testTorrentingCapability since the last week, it's always showing the _Looks like you do not have an internet connection or are behind a firewall._ (when my internet is working fine).

Also, it's [waiting for the app component to mount](https://github.com/statechannels/monorepo/blob/41b7765ece53510bb6c9d603aa2c756b01fa1984/packages/web3torrent/src/App.tsx#L37), when I think it should run even before the library's `enable()` and then just save the result (so that the UI doesn't need to wait for the timeout). 

**To Reproduce**
1. Open Web3Torrent

**Environment:**
 - Affected packages: web3torrent
 - OS: Linux
 - Browser: chrome
 - Version: 80

**Comment by geoknee** [comment]
We could move the line you linked to the class constructor http://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/http://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/ .

**Comment by geoknee** [comment]
...along with the preceding `context.enable()`.

**Comment by geoknee** [comment]
Actually that won't work because the methods are `async`.

**Comment by spersico** [comment]
I would just run `enable()` in the class constructor just the same, along with the `testTorrentingCapability()`. 
The current `enable()` doesn't return anything. We don't need to wait for it.
We could have a `connectionStatus` prop, which `testTorrentingCapability()` updates internally.

This way, `connectionStatus` could theoretically be "not-tested" initially, and "optimum", "with-issues" or something like that, and solve it in the promise resolution.

**Comment by spersico** [comment]
The UI would then just watch for the web3torrent prop change.

**Comment by geoknee** [comment]
This issue is possibly state, we should get an updated bug report.

**Comment by geoknee** [comment]
If this can't be made to work reliably, we could just disable the test, since public wifi is not something many people are using at the moment.
