### ISSUE TITLE
[xstate-wallet] Add favicon

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1316]
Would be nice if MetaMask popup showed state channels logo instead of the ( L ) placeholder:

<img width="796" alt="Screenshot 2020-03-27 at 10 51 51" src="https://user-images.githubusercontent.com/1833419/77748864-f7f86a80-7018-11ea-9d96-a91a741b8333.png">

I believe it gets the logo from the site's favicon (see e.g. web3torrent).

**Comment by kerzhner** [comment]
This would be especially nice for production.
<img width="357" alt="Screen Shot 2020-05-07 at 8 30 52 AM" src="https://user-images.githubusercontent.com/1062379/81317878-43ebf580-9042-11ea-83b0-ed2b65fefe0e.png">

**Comment by geoknee** [comment]
Via #1768
