### ISSUE TITLE
[web3t] Remove or modify example torrents

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1331]
If you load the app and click "Download" next to (e.g.) the Sintel torrent, you start downloading without any state channels stuff getting in your way. 

We could either

a) delete these for now
b) add a check for downloaders to not connect to non web3t clients (uploaders already have one, I think)

**Comment by spersico** [comment]
We would have to have some sort of seeder always online, that automatically accepts connections, and serves the example files?.

Another thing to define is, what should we do with the funds gained for seeding those files?

**Comment by geoknee** [comment]
> We would have to have some sort of seeder always online, that automatically accepts connections, and serves the example files?.

Yes this could just be a machine running our web3torrent client.
