### ISSUE TITLE
[Bug] Performance Degradation when using real payments

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1335]
**Describe the bug :bug:**
I'm having performance degradation issues in web3torrent using xstate.
Basically, the problem is that on a big torrent sharing the tabs starts getting really slow progressively. To the point where at multiple times the download/upload speeds shows 0B/s, almost constantly, 'till the moment a payment comes through, the paid data gets transferred, and then it's 0B/s again for a while.
Besides that, the CPU usage has really big spikes (like, Youtube reproducing 1440p videos level spikes), and the tabs gets really slow after a while.
This wasn't happening using the fake channel provider, so I'm assuming that it's something to do with the xstate-wallet, or the channel-provider, or the channel-client, or something on that line.

This is creating problems with torrenting in web3torrent because, when the messages start getting slower, the entire download gets slower and slower.
A super visual way to see this, is that on a 10mb torrent, the torrent is downloading at around 30-80kb/s, and by the end of the 10mb torrent, it's around 13kb/s.

**To Reproduce**
Steps to reproduce the behaviour:
1. Checkout to my branch: `sp/w3t-buffer-improvements-and-fixes` (this is to solve some issues with closing channels at the wrong time, and unexact payments that happened to me in the master branch).
2. Open Shared Ganache
3. Open Xstate-Wallet using: `USE_VIRTUAL_FUNDING= ADD_LOGS=true yarn start`
4. Open Web3Torrent using: `REACT_APP_AUTO_FUND_LEDGER= yarn start`
5. Upload a 20mb file, see download speed decrease and CPU and RAM increase progressively.

**Expected behaviour**
The speed should be somewhat stable, the behaviour should be somewhat constant, from beginning to end of the download.

**Comment by lalexgap** [comment]
Just beginning to investigate. It looks like this might be due to the `channel-provider` creating a lot listeners.
![image](https://user-images.githubusercontent.com/1620336/77954434-748e8180-7283-11ea-9da2-30469935b1ae.png)

![image](https://user-images.githubusercontent.com/1620336/77954484-82dc9d80-7283-11ea-8753-0e9d8f55b3c5.png)

**Comment by lalexgap** [comment]
I'm having trouble reproducing this. I'm seeing download speeds range from `15kbps` to `40kbps` but I'm not seeing any degradation of download speed (that I can notice) as the torrent downloads. I've also done a profile in chrome when downloading and I'm not seeing anything too suspicious. 
![image](https://user-images.githubusercontent.com/1620336/77964202-8bd56b00-7293-11ea-9bce-295d224232a6.png)

**Comment by snario** [comment]
What's the latest on this? Larger files seem to be working well for me and in our team standups. @spersico

**Comment by spersico** [comment]
I think we can close this, IIRC the performance issue's cause was due to an inefficient algorithm in xstate wallet, when dealing with the internal states of a channel entry. @lalexgap fixed that
