### ISSUE TITLE
Garbage Collection of Old states in ChannelStoreEntry uses a lot of CPU

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1344]
Currently most of the cpu usage in chrome is taken by attempting to clean up old states. Specifically this call https://github.com/statechannels/monorepo/blob/d2ab09459ca502ce460122dd3e9d313709d80596/packages/xstate-wallet/src/store/channel-store-entry.ts#L180

We should probably optimize this or remove it (perhaps GC on start up?)

**Comment by andrewgordstewart** [comment]
The simplest thing for now is probably to remove it, though that might make debugging a pain (which state hash of these 10 has turn 4?)

Past that, I don't see an obvious benefit of using a `{ [stateHash: string]: StateVariables }` data structure to store the state variables. More sensible to me is storing an array, sorted by `turnNum`, which makes this easier to optimize.

**Comment by lalexgap** [comment]
It looks like the garbage collection isn't actually cleaning up `stateVariables` which explains why we see the download speed slowing down the longer the torrent is running.

**Comment by lalexgap** [comment]
> It looks like the garbage collection isn't actually cleaning up `stateVariables` which explains why we see the download speed slowing down the longer the torrent is running.

The root cause was that our `supported` check only returns `true` when the number of signatures on a state is equal to the participants.

so `supported.turnnum` was always 3,  since new states coming in from the app don't have two signatures.
