### ISSUE TITLE
Chrome background tab throttling slows download speeds

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1345]
If you're running web3-torrent in chrome, with the uploader tab in the background you'll get a very slow download speed. 

If you simply move the tab from the background into the foreground (so you have both tabs visible) the download speed will immediately jump.

With the tab in the background I saw a speed of `30kbs` but by simply moving it to the foreground speeds jumped to `2mbs`

I suspect the throttling outlined here is the cause: https://developers.google.com/web/updates/2017/03/background_tabs 

I'm not sure if there's any practical way around this but I just want to flag this for now.

**Comment by geoknee** [comment]
I notice there is a (partial) exception made for webRTC connections (which we have), and a full exception made for tabs that play audio (which we don't have). 

...

**Comment by snario** [comment]
Maybe add a note in the FAQ / Q&A of the app.

**Comment by geoknee** [comment]
There is now a note in the FAQ. Closing as no further action to be taken.
