### ISSUE TITLE
Refactor storage to just store the `signatures` on the entry of the `stateVariables` array

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1358]
Does it make sense to refactor this to just store the `signatures` on the entry of the `stateVariables` array? (so that they are guaranteed to be aligned)

_Originally posted by @andrewgordstewart in https://github.com/statechannels/monorepo/pull/1353_

**Comment by lalexgap** [comment]
I think this and #1358 are the same.
