### ISSUE TITLE
Set up set of standard .env variables

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1377]
We should set of a set of standard`.env` variables for `xstate-wallet`, `web3torrent`, and `simplehub` that allow us to test virtual funding without indexed db.

**Comment by lalexgap** [comment]
Is this still something we want to do? If so @andrewgordstewart do you have a recommended list of `.env` variables?

**Comment by kerzhner** [comment]
Would https://github.com/statechannels/monorepo/pull/1501 address this issue?

**Comment by geoknee** [comment]
@kerzhner I would say that it does, especially with #1544
