### ISSUE TITLE
Handle disconnect error case

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1381]
Handle the scenario where a user gets disconnected mid connection.

We should handle this as gracefully as we can.

**Comment by junjizhi** [comment]
@lalexgap Do we currently have a timeout somewhere when this happens?

**Comment by lalexgap** [comment]
> @lalexgap Do we currently have a timeout somewhere when this happens?

I don't think we currently have a timeout anywhere when this happens unfortunately.

**Comment by lalexgap** [comment]
> > @lalexgap Do we currently have a timeout somewhere when this happens?
> 
> I don't think we currently have a timeout for this but I'm not 100% sure.

**Comment by lalexgap** [comment]
Closing this as it's overly broad
