### ISSUE TITLE
Implement UI around budgets in web3torrent

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1382]
Add some more information about budgeting to the UI and the ability for the user to create a budget on demand.

We should probably include information about budgets on the welcome screen with a link of some kind that the user can click to create a budget.

We will also need a UI for creating a budget to allow the user to specify the amount for the budget.

**Comment by junjizhi** [comment]
> the ability for the user to create a budget on demand.

Are we going to reuse `approveBudgetAndFund(...)` for this? Or we create a new method?

**Comment by lalexgap** [comment]
> > the ability for the user to create a budget on demand.
> 
> Are we going to reuse `approveBudgetAndFund(...)` for this? Or we create a new method?

We should use `ApproveBudgetAndFund`

**Comment by junjizhi** [comment]
@lalexgap 

I'm going to take a stab on this ticket.

> We should use ApproveBudgetAndFund

Is is possible a user approves a 5 ether budget first, and then decrease the budget to 3 ether, but your actual spent is > 3 ether? What would happen?

Looking at implementation of `ApproveBudgetAndFund`, it doesn't enforce a rule that users can't downsize the budget.

**Comment by lalexgap** [comment]
> @lalexgap
> 
> I'm going to take a stab on this ticket.
> 
> > We should use ApproveBudgetAndFund
> 
> Is is possible a user approves a 5 ether budget first, and then decrease the budget to 3 ether, but your actual spent is > 3 ether? What would happen?

For the initial implementation I think we should assume that once you create a budget with the hub you can't change it.  So no downsizing/upsizing your budget.
>
> Looking at implementation of `ApproveBudgetAndFund`, it doesn't enforce a rule that users can't downsize the budget.

We should probably throw an error in `ApproveBudgetAndFund` if the user already has a `budget` and it is called.
