### ISSUE TITLE
Finish messaging serde

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1410]
Message serialization/deserialization fails in the e2e test with the hub. These commands should reproduce it on 5c16fd6a806142e433355c44d4aedd6b7179b388

```
$ monorepo ❯ yarn start:shared-ganache
$ simple-hub ❯ FIREBASE_PREFIX=web3t-andrew  NODE_ENV=development yarn hub:watch > messages.log
$ web3torrent ❯ REACT_APP_FIREBASE_PREFIX=web3t-andrew REACT_APP_FUNDING_STRATEGY= yarn start
$ xstate-wallet ❯ ADD_LOGS=true USE_INDEXED_DB= yarn start
$ e2e-tests ❯ ADD_LOGS=true REACT_APP_FUNDING_STRATEGY=Virtual HEADLESS=FALSE yarn test web3tor
```

See https://github.com/statechannels/monorepo/commit/362461d6803c5cc5881cc1504492452f23e2ef15 for an attempted fix. This fixes the unexpected `type` property error at 5c16fd6a806142e433355c44d4aedd6b7179b388, but reveals another `expected property 'outcome' missing` error.

**Comment by andrewgordstewart** [comment]
I did not determine whether the problem code was a part of the `simple-hub`, `xstate-wallet` or `web3torrent`.

**Comment by lalexgap** [comment]
FYI I had to override `REACT_FIREBASE_URL` to get things working. 
```REACT_APP_FIREBASE_URL=https://rock-paper-scissors-dev-4ff8d.firebaseio.com REACT_APP_FIREBASE_PREFIX=web3t-gap REACT_APP_FUNDING_STRATEGY= yarn start```

The simple hub seems to default to the external firebase url ` Listening on database https://rock-paper-scissors-dev-4ff8d.firebaseio.com`
