### ISSUE TITLE
Refactor App.tsx to function component

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1412]
I am in factor of refactoring this class component to a function component + hooks. You might be able to reuse the work on [this branch](https://github.com/statechannels/monorepo/commit/4218e299c5f053b8e3718e6cc15d3f816b237bee#diff-aaa8f7e584ffc4ebc36d61e9313a7075)

_Originally posted by @kerzhner in https://github.com/statechannels/monorepo/pull/1363_

**Comment by geoknee** [comment]
Fixed in #1415
