### ISSUE TITLE
Web3torrent relies on callbacks fired in a specific order.

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1439]
One example is:
Whether or not [this](https://github.com/statechannels/monorepo/blob/608147a71b358ed7148d1d4f8589cf88349507f5/packages/web3torrent/src/library/web3torrent-lib.ts#L287) is undefined (or, harder to detect, stale data) depends on whether [this callback (A)](https://github.com/statechannels/monorepo/blob/608147a71b358ed7148d1d4f8589cf88349507f5/packages/web3torrent/src/library/web3torrent-lib.ts#L277) or [this callback (B)](https://github.com/statechannels/monorepo/blob/608147a71b358ed7148d1d4f8589cf88349507f5/packages/web3torrent/src/clients/payment-channel-client.ts#L75-L77) fires first.
- If (A) fires before (B), then the new channel result is not yet stored in the cache

There could be other places that depend on callback ordering.

## Proposed solutions
1. Use rx-js observables to replace the channel cache
2. Refactor `paymentChannelClient.onChannelUpdated` to ensure that the callbacks are called _after_ `paymentChannelClient.channelClient.onChannelUpdated` callbacks

**Comment by andrewgordstewart** [comment]
Regarding 2, we could
1. refactor [callback (B)](https://github.com/statechannels/monorepo/blob/608147a71b358ed7148d1d4f8589cf88349507f5/packages/web3torrent/src/clients/payment-channel-client.ts#L75-L77) to manage the channel cache as a private variable, and
- emit a `'NewChannelResult'` event when `channelClient` emits `'ChannelUpdated'`
2. refactor [`PaymentChannelClient.onChannelUpdated`](https://github.com/statechannels/monorepo/blob/608147a71b358ed7148d1d4f8589cf88349507f5/packages/web3torrent/src/clients/payment-channel-client.ts#L179-L187) to
- emit the most recent channel result (if exists) on subscription
- emit a new channel result when `'NewChannelResult'` is emitted

**Comment by spersico** [comment]
Fixed in makePayment by adding a ReplaySubject from the channelClient in #1521 
It remains to be decided if this change should expand into other parts of the codebase

**Comment by geoknee** [comment]
We _might_ want to roll that pattern out to closing a channel: 
https://github.com/statechannels/monorepo/blob/ce363582709a225c7a76462d56de10e267e2cdc0/packages/web3torrent/src/clients/payment-channel-client.ts#L209-L213

especially if we want to wait until it is my turn before making the `closeChannel` call.  There might be alternative strategies for closing a channel that we could employ, subject to support in the wallet.

**Comment by lalexgap** [comment]
Closing as remaining work can be done in #1724
