### ISSUE TITLE
Investigate what's needed to get reloading Web3torrent pages working

### ISSUE THREAD

**Issue by junjizhi** [statechannels/monorepo#1453]
**Problem description :confused:**
Right now reloading web3torrent page, we lose the existing channels and budget. 

**Describe the solution you'd like :rocket:**
Investigate what's needed to get the page keep those data.

**Comment by andrewgordstewart** [comment]
Off the bat, web3torrent does initialize, and thus does not communicate with the wallet on load. So, to view budgets on reload, wallet initialization would need to happen on load.

This used to be the case, and was changed for a specific reason (that I am unaware of.)

**Comment by junjizhi** [comment]
Currently we only call [enable()](https://github.com/statechannels/monorepo/blob/master/packages/web3torrent/src/clients/web3torrent-client.ts#L29) web3torrent client when user initiates an upload or download action. The `enable()` function then relies on payment channel client to [communicate with the wallet](https://github.com/statechannels/monorepo/blob/master/packages/web3torrent/src/clients/payment-channel-client.ts#L86). I think it doesn't happen on load because we want better UX (?). We could change the code to let the communication happen on page load though.

Ideally, we store some session data somewhere (firebase? cookies?), so that when users refresh the page, we can retrieve the budget and channel data. The next question is figure the storage.

One crucial piece of data is the signing address. We can use it as a key to retrieve data from storage.

It's not clear to me how wallet generates those signing addresses. It seems to be random. It needs to be deterministic so that when we refresh the page, we can still find out the same address.

@andrewgordstewart @geoknee What do you think? Do I miss anything?

**Comment by junjizhi** [comment]
> It's not clear to me how wallet generates those signing addresses. It seems to be random. It needs to be deterministic so that when we refresh the page, we can still find out the same address.

I confirm that the address generation is deterministic. I saw the random behaviour probably because my local indexdb was corrupted. The issue went away after I cleared local indexdb.

> Currently we only call enable() web3torrent client when user initiates an upload or download action. The enable() function then relies on payment channel client to communicate with the wallet. I think it doesn't happen on load because we want better UX (?). 

If we call the `enable()` function on page load, it change the behaviour. 

**Before**: Approve budget prompt on upload
**After**: Approve budget prompt right away on page load

So we need to change the integration tests as well. 

Do you guys see an issue with this? @andrewgordstewart @geoknee

**Comment by andrewgordstewart** [comment]
> > It's not clear to me how wallet generates those signing addresses. It seems to be random. It needs to be deterministic so that when we refresh the page, we can still find out the same address.
> 
> I confirm that the address generation is deterministic. I saw the random behaviour probably because my local indexdb was corrupted. The issue went away after I cleared local indexdb.

> Just to confirm, the address _generation_ is random, but it should only happen _once_. So, `getAddress` should return a random address when the store is initialized, but once it is initialized, it should return the same address each time.
> 
> If we call the enable() function on page load, it change the behaviour.
> 
> Before: Approve budget prompt on upload
> After: Approve budget prompt right away on page load
> 
> So we need to change the integration tests as well.

I think `enable()` used to be called on page load, and this was changed for a specific UX reason. I think @spersico would know this?

**Comment by snario** [comment]
Two quick notes.

1. Calling `ethereum.enable()`, triggering a MetaMask pop-up, is best done after some sort of user action. This is an opinion held my me and some others that is mostly about avoiding pop-ups on page load if we can help it and instead associating them with user-triggered actions.

2. It should be possible to approve a budget without requiring `ethereum.enable()`, but we can't do this right now because `approveBudgetAndFund` is a single API method as opposed to `approveBudget` and `fund`. Just FYI.

**Comment by snario** [comment]
As a follow-up to #2 above, it shouldn't be an issue to call `GetBudget` from `web3torrent` to the `xstate-wallet` on page load. If there is no budget, the method should return `null` (or equivalent) and if it is present then it should return the budget. There is no need for `ethereum.enable()` to be called in this situation.

**Comment by junjizhi** [comment]
@snario Good notes.

Above we are mainly concerning the `WebTorrentPaidStreamingClient.enable()` which enables the payment channel client. Sounds like we need to decouple we the enable() calls so that the payment channel client gets enabled on page load, but delay `ethereum.enable()` until upload/download. I will look into that and see if it's possible.

**Comment by junjizhi** [comment]
Looks like this issue will be addressed in https://github.com/statechannels/monorepo/pull/1528
