### ISSUE TITLE
Unable to view app (CSS styling)

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1455]
I'm unable to view all the data on web3torrent without changing the size of the screen or zooming out.

This is probably a simple styling issue?

![missing-info](https://user-images.githubusercontent.com/8432675/79478695-92b4eb00-7fc0-11ea-8917-1d455d02681f.gif)

**Comment by geoknee** [comment]
Could this be a Chromium-specific problem?

**Comment by andrewgordstewart** [comment]
It might be, since it seems like it behaves differently on Chrome.

**Comment by lalexgap** [comment]
@andrewgordstewart have you seen this recently?

**Comment by andrewgordstewart** [comment]
I'll check in a few minutes.

**Comment by lalexgap** [comment]
@andrewgordstewart I'm going to close this one, feel free to reopen if you're still seeing this.
