### ISSUE TITLE
[web3torrent] React memory leak

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1469]
<img width="1260" alt="Screen Shot 2020-04-17 at 10 04 51 AM" src="https://user-images.githubusercontent.com/1062379/79595016-f90a3e00-8092-11ea-89dd-dffe98898b1b.png">

This looks like related to the torrent status work. To reproduce, create a seeder and a leecher and share a file.

**Comment by kerzhner** [comment]
I believe this is still an occuring issue.

**Comment by snario** [comment]
I've never seen this error before. Are you sure this is how to reproduce it?

**Comment by kerzhner** [comment]
> I've never seen this error before. Are you sure this is how to reproduce it?

You are right, the repro instructions are pretty poor. I will update the instructions next time I see the error.

**Comment by kerzhner** [comment]
Closing in favor of https://github.com/statechannels/monorepo/issues/1835
