### ISSUE TITLE
RTCErrorEvent

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1472]
**Describe the bug :bug:**
A error message is appearing in console. There isn't a consequence that I can see of this error. 
![image](https://user-images.githubusercontent.com/10502605/79602386-c4ad7680-80c0-11ea-91da-b8eb3b09d8f5.png)

**To Reproduce**
Seed and Leech a Torrent (in different tabs) you should see this error in both tabs.

**Additional context**

**Comment by kerzhner** [comment]
Seeing an integration failure with this error: https://app.circleci.com/pipelines/github/statechannels/monorepo/5197/workflows/69975bec-f782-42c6-a10e-ffd9e6e9e724/jobs/19237

**Comment by andrewgordstewart** [comment]
If we get these in, we might be able to debug this!
https://github.com/statechannels/monorepo/pull/1473
https://github.com/statechannels/monorepo/pull/1471

**Comment by spersico** [comment]
@kerzhner and I just took a good look at it, and it's about the `checkTorrentInTracker` function. I'm taking a look right now
