### ISSUE TITLE
[web3torrent] Has likely outgrown react-scripts

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1494]
It might be time to [eject](https://create-react-app.dev/docs/available-scripts/#npm-run-eject). 

Specifically, it would be nice to change the webpack configuration to allow for environment variables that do not have the `REACT_APP` prefix. This is a somewhat minor issue at the moment. If more pain points like this crop up, it could be time to eject.

**Comment by snario** [comment]
We ejected
