### ISSUE TITLE
Enable segment for xstate-wallet

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1518]
Some tool which simply shows information about xstate-wallet usage in the wild. For example:
- [ ] 1. How many wallets exist?
- [ ] 2. How much money is in those wallets?
- [ ] 3. How many API calls of various types have been made?
- [ ] 4. What is the size of the average users store in KB?
- [ ] 5, What “sites” are the most used?
- [ ] 6. How many challenges occur in the wild?

Again these can be “opt-in”, but it would be very helpful for us to understand how people are using this.

**Comment by snario** [comment]
Added to Web3Torrent. Adding to wallet now!

**Comment by tomclose** [comment]
@snario is this done in the wallet?

**Comment by lalexgap** [comment]
Add analytics (Amplitude?) and hook up to segment

**Comment by andrewgordstewart** [comment]
I have narrowed the scope of this issue to simply enabling segment in xstate wallet (it is already enabled in web3torrent).

I'll tackle 1-3, and think about 4.

I will ignore 5-6, since they are pretty meaningless questions right now.
