### ISSUE TITLE
Production logs and errors

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1519]
A single place for all user logs and errors for all packages. Primarily used for debugging issues experienced by users in the wild. Should allow for filtering on various fields like channelId, environment, etc.

We can use something like Splunk (though that might be overkill?)

**Comment by snario** [comment]
Mirror of #983

**Comment by andrewgordstewart** [comment]
One short-term solution here is to package up the `LogBlob` on error and send to sentry.

Those logs can be large (A: is that a problem in an of itself?) which may mean uploading 30MB of data (B: is that a problem?)

Regardless of whether we do this, (A) would imply that we consume a lot of user upload bandwidth when sending logs. That's worth considering regardless of whether we upload a single `.log` file containing the contents of `LogBlob.blob`, or whether we stream many, many log statements.
