### ISSUE TITLE
Use IndexedDB/Dexie backend in wallet tests

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1526]
Currently, wallet tests use a MemoryBackend.

We would have more coverage of store code by using the IndexedDB backend (or, in the future, the Dexie backend).

The naive approach of setting the backend of the `TestStore` to be the `IndexedDB` backend won't work, since using https://github.com/dumbmatter/fakeIndexedDB will end up with wallets using the _same store_.

**Comment by andrewgordstewart** [comment]
💡 can we just use different database names in different stores?

**Comment by kerzhner** [comment]
@andrewgordstewart should we close this issue?

**Comment by andrewgordstewart** [comment]
The wallet tests still use the Memory backend. If we're ok with that, we should close this.

**Comment by snario** [comment]
Integration tests use IndexedDB backend, so we should be good here right @andrewgordstewart ?

**Comment by andrewgordstewart** [comment]
The wallet tests still use the memory backend, for the most part. (I think there are one or two that use the indexedDB backend.)

Maybe we want to keep using the memory backend, I don't know.
