### ISSUE TITLE
Store should emit `ChannelUpdated` when entry is actually updated

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1535]
https://github.com/statechannels/monorepo/blob/master/packages/xstate-wallet/src/store/store.ts#L394-L395

Perhaps the event should be emitted  as a part of a `setChannel` callback.

**Comment by snario** [comment]
It emits an internal event:

https://github.com/statechannels/monorepo/blob/ca2d3bb4f35b9c6af0f07917b5b7dd0514efcba2/packages/xstate-wallet/src/store/store.ts#L347-L348

Are you suggesting this should be an external event?

**Comment by andrewgordstewart** [comment]
This is probably a better link:
https://github.com/statechannels/monorepo/blob/8b47f6a2a2ccbf39249c9074ce9aeef4dc1dea03/packages/xstate-wallet/src/store/store.ts#L394-L400

The original issue was that the channel-updated event was not emitted at the point when the channel is updated. It was emitted _approximately_ when the channel is updated, but not immediately after.

Now that we use transactions, the event should be emitted at the point when the transaction is committed (that's exactly the point in time that the channel is considered updated). That's what's happening [now](https://github.com/statechannels/monorepo/blob/37ebb2b/packages/xstate-wallet/src/store/store.ts#L406-L408), so we can close this.
