### ISSUE TITLE
[xstate-wallet] Withdrawal from directly funded channels

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1546]
This is currently stubbed out: 

https://github.com/statechannels/monorepo/blob/8c0a3ef10dcdaa58a99b88453b3d2b9b6d6627c7/packages/xstate-wallet/src/workflows/conclude-channel.ts#L86-L88

**Comment by snario** [comment]
https://github.com/statechannels/monorepo/pull/1834
