### ISSUE TITLE
Flickering integration test -- `the tx doesn't have the correct nonce.`

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1577]
From [these logs](https://21322-209829093-gh.circle-artifacts.com/0/packages/simple-hub/pino.log), from [this test run](https://app.circleci.com/pipelines/github/statechannels/monorepo/5566/workflows/b569fba8-4b85-41d1-9ead-e5b955e1e595/jobs/21322).

Re-running the failed job, and [it passed](https://app.circleci.com/pipelines/github/statechannels/monorepo/5566/workflows/06d58567-0145-4d1c-b2a9-e525ae0cd083/jobs/21334).

**Comment by kerzhner** [comment]
Per conversation with @andrewgordstewart, the next step is to try upgrading the `simple-hub` to ethers v5 per this comment https://github.com/ethers-io/ethers.js/issues/451#issuecomment-472722960

**Comment by andrewgordstewart** [comment]
Another thing to do is to improve the logging so that we can see:
- what transaction is submitted, with what nonce, by whom

In case we are using the same private key between different signers (eg. simple-hub and one of the leechers), we should be able to detect that from the logs.

**Comment by kerzhner** [comment]
Keeping this issue open to confirm that https://github.com/statechannels/monorepo/pull/1697 actually fixes the issue.

**Comment by andrewgordstewart** [comment]
When I add https://github.com/statechannels/monorepo/pull/1441/commits/3d5b50581cffb5ab95c095fc05cd7d8f212a1521, and run the "stress" test on that branch, all of the browsers which do deposit log
```
 "Deposit successful from 0xD9995BAE12FEe327256FFec1e3184d492bD94C31"
```

This is without using dappeteer, and _with_ [different ganache account indexes](https://github.com/statechannels/monorepo/blob/e297da3797251bb4b9d74d0232bb8ef15ba0c6a9/packages/e2e-tests/puppeteer/__tests__/web3torrent/stress.test.ts#L66-L71) passed to `setupFakeWeb3`. (I confirmed by [looking at the browser output logs](https://github.com/statechannels/monorepo/pull/1441/commits/8dbcbd24b7b889ba4727bd063a20193bfd7cf647) _different_ `selectedAddress` values.)

My conclusion is that _without_ dappeteer, and _with_ different `selectedAddress` values, the fake web3 provider still uses the _same_ signing key in the integration tests. I'm pretty confident that the same is true _with_ using dappeteer, and that the [`getProvider`](https://github.com/statechannels/monorepo/blob/master/packages/xstate-wallet/src/utils/contract-utils.ts#L25) call always uses the _first_ address in the integration tests.

The positive outcome here is that there's no evidence of any bug within the simple-hub. I also added some logging to the simple-hub, and was able to produce logs where
- the hub had several deposits queued up
- the [critical block of code](https://github.com/statechannels/monorepo/blob/master/packages/simple-hub/src/blockchain/eth-asset-holder.ts#L41-L69) was only accessed one at a time
- yet, the deposit failed due to the incorrect nonce error

**Comment by kerzhner** [comment]
Unless there are objections, it is likely safe to close this issue. It seems that whenever we see nonce errors on the hub, the underlying cause is the use of the same chain address between the hub and one of the participants.
