### ISSUE TITLE
Transaction error in production

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1589]
<img width="1269" alt="Screen Shot 2020-04-28 at 1 05 28 PM" src="https://user-images.githubusercontent.com/1062379/80532458-0bb52a80-8951-11ea-8f07-c2d5256352ff.png">

Using the following url to test: https://web3torrent.statechannels.org/file/85c419f2a49f77c37eae541df77d82c4a8c7cbd9?name=symbol.svg&length=1470.

**Comment by geoknee** [comment]
I saw this too, but was able to retry with higher gas price and then the tx succeeded. This also explains why the problem wasn't showing up in my `persistent-seeder` work (which uses dappeteer and sets gas price parameters explicitly). 

https://github.com/MetaMask/metamask-extension/issues/7286

**Comment by lalexgap** [comment]
> I saw this too, but was able to retry with higher gas price and then the tx succeeded. This also explains why the problem wasn't showing up in my `persistent-seeder` work (which uses dappeteer and sets gas price parameters explicitly).
> 
> [MetaMask/metamask-extension#7286](https://github.com/MetaMask/metamask-extension/issues/7286)

@kerzhner Are you ok to close this one? (I just tried the link and the transaction sent through fine for me as well)
