### ISSUE TITLE
Fix CSS overflow on "approve budget" UI

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1599]

**Comment by lalexgap** [comment]
@snario Do you have more details? Was this only on production?

**Comment by snario** [comment]
It's because the site name is `web3torrent.statechannels.org` which is too long of a string to be on the same line as the text before it, so there's a newline added.
![image](https://user-images.githubusercontent.com/1933029/80768324-179f1900-8b18-11ea-9b61-295f7110c9ce.png)
