### ISSUE TITLE
State machine Transitions are logged multiple times

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1612]
State machine transitions get logged out multiple times, making it hard to use the `pino` logs for debugging. In one case I saw a transition logged 36 times.

From @andrewgordstewart :
https://github.com/statechannels/monorepo/blob/master/packages/xstate-wallet/src/channel-wallet.ts#L208

onTransition, you call logTransition on each of your children (even if they are already logging their transitions)

**Comment by andrewgordstewart** [comment]
See https://github.com/statechannels/monorepo/pull/1558/commits/5c7fe2e3d0dad932dc182be87678a4824fe01a29
