### ISSUE TITLE
Multiple join channel workflows

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1628]
From [here](https://app.circleci.com/pipelines/github/statechannels/monorepo/5753/workflows/3cb18aa2-cd32-4efd-b86d-5b9940ffd53b/jobs/22595/artifacts),
>Browser 1 logged There is already a workflow running with id JOIN_CHANNEL-0x229f8f4d06b1c2340aec4d028c589210feee3520610bb5b27402bf076224a0f6, no new workflow will be spawned

My understanding was this warning is in place specifically because RPS was calling JoinChannel multiple times -- now, perhaps web3torrent is as well?

**Comment by snario** [comment]
Might be related to #1635

**Comment by snario** [comment]
Was this fixed recently @andrewgordstewart?

**Comment by andrewgordstewart** [comment]
I'm not aware of anything that would have changed this.
