### ISSUE TITLE
Rimble ConnectionBanner does not work in production

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1641]
I can switch between network willy-nilly but never see any kind of warning. 

It seems to work locally. Perhaps this is because wallet and app are served from the same domain locally, but different domains in production? Recall that the wallet is the only one that calls ethereum.enable and directly speaks to metamask.

**Comment by geoknee** [comment]
This issue means that, faced with a unready App :

https://github.com/statechannels/monorepo/blob/bfc9c6fbaf9c3d1b3fc9287e527fa3fbad1d73b3/packages/web3torrent/src/App.tsx#L36

it is difficult to infer the root problem. If the banner worked, you can rule out one of the possibilities by switching to the correct network.

**Comment by geoknee** [comment]
It would be good to gather some more data on who is seeing this problem on production. Also, to know what happens when metamask has the chrome feature "onClick" enabled.

**Comment by snario** [comment]
I've not seen the banner "not work" on production @geoknee. It works for me on production. Is this still an issue?

**Comment by geoknee** [comment]
Let's close it.
