### ISSUE TITLE
e2e script fails and times out

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1675]
Occasionally the direct funding integration test fails and times out.

It seems that the `run-e2e.sh` script doesn't properly report an error in this case?

```./bin/run-e2e.sh: line 43: exit_status: unbound variable```

**Comment by andrewgordstewart** [comment]
Is there a circle run you could link?

**Comment by lalexgap** [comment]
> Is there a circle run you could link?

Just about to add it:
https://app.circleci.com/pipelines/github/statechannels/monorepo/5863/workflows/374c320e-9e09-4ff4-916c-c976f3355cf5/jobs/23276/steps

**Comment by lalexgap** [comment]
The `e2e` script failing may be fixed by https://github.com/statechannels/monorepo/pull/1658

**Comment by andrewgordstewart** [comment]
Per discussion with @geoknee, the `run-e2e.sh` script may have outlived its usefulness:
1. the most useful part is starting all the servers. `start-servers.sh` does this, and seems to more reliably clean up child processes
2. The second most useful part is being able to quickly reproduce what the integration tests happen on circle.
3. Using `run-e2e.sh` in circle makes it hard to separate console output related to starting the servers, and output related to running the tests

If we
A. get rid of `run-e2e.sh`,
B. create a yarn command which waits for the servers to be running, then runs the test
then
- circle can start the servers in a background step
- it's easier to see what went wrong
- we don't have to learn how to manage background processes

**Comment by lalexgap** [comment]
Since run-e2e has been removed I think we can close this. We can open another issue if the underlying error pops up.
