### ISSUE TITLE
Error: Attempting to sign a stale state

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1693]
```
 FAIL  puppeteer/__tests__/web3torrent/stress.test.ts (35.379s)
  One file, three leechers, one seeder
    ✕ allows peers to start torrenting (33680ms)
  Two files, three seeders, three leechers
    ○ skipped allows peers to start torrenting

  ● One file, three leechers, one seeder › allows peers to start torrenting

    Error: Attempting to sign a stale state
```

At 21024fc04a7ec82976e32b4142a65d3f7be5d3c8 (commit hash may change with future rebases)
<img width="945" alt="Screen Shot 2020-05-05 at 12 12 01 PM" src="https://user-images.githubusercontent.com/8432675/81105998-b4233b80-8ec9-11ea-9a10-1bee594cadd7.png">

**Comment by andrewgordstewart** [comment]
https://app.circleci.com/pipelines/github/statechannels/monorepo/6464/workflows/80e25d76-6a75-4400-9534-6bb9944ec8c0/jobs/27228/steps

**Comment by andrewgordstewart** [comment]
https://app.circleci.com/pipelines/github/statechannels/monorepo/6452/workflows/7855cb39-d229-4a54-8210-efaf11791581/jobs/27145

**Comment by snario** [comment]
I think the `updateChannel` single transaction store method fixed this issue
