### ISSUE TITLE
No circle output in e2e test

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1716]
https://app.circleci.com/pipelines/github/statechannels/monorepo/6028/workflows/b9552df5-e38e-478d-99af-336b24f2564e/jobs/24372/steps

```
#!/bin/bash -eo pipefail 
(cd packages/e2e-tests && yarn test web3torrent) 
yarn run v1.17.3
 
$ jest --bail --runInBand web3torrent
 
Waiting for servers
 
Servers started
 
 
Too long with no output (exceeded 10m0s): context deadline exceeded 
```

**Comment by geoknee** [comment]
related? https://github.com/statechannels/monorepo/pull/1713

**Comment by andrewgordstewart** [comment]
>Servers started

This indicates that the `waitOn` promise resolved, so it shouldn't be the culprit.

**Comment by andrewgordstewart** [comment]
I think the issue was [this](https://github.com/statechannels/monorepo/pull/1763/files#diff-6a600906873d4a4e1526e77b9f84086cL6).

- `HEADLESS` was set to `true` in some integration test environment variables, something that I had not anticipated when setting the `100_000` timeout.
- Therefore, jest would wait to timeout for longer than circle, sometimes with _no output at all_
