### ISSUE TITLE
Use channelClient.channelState for closing a channel

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1724]
We _might_ want to roll that pattern out to closing a channel: 
https://github.com/statechannels/monorepo/blob/ce363582709a225c7a76462d56de10e267e2cdc0/packages/web3torrent/src/clients/payment-channel-client.ts#L209-L213

especially if we want to wait until it is my turn before making the `closeChannel` call.  There might be alternative strategies for closing a channel that we could employ, subject to support in the wallet.

_Originally posted by @geoknee in https://github.com/statechannels/monorepo/issues/1439#issuecomment-619083364_

**Comment by snario** [comment]
This seems to work well. Do you think we still need to do this? cc @lalexgap 
@spersico 

https://github.com/statechannels/monorepo/blob/ca2d3bb4f35b9c6af0f07917b5b7dd0514efcba2/packages/web3torrent/src/clients/payment-channel-client.ts#L207-L217
