### ISSUE TITLE
js bundle takes too long to load

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1730]
It is roughly 30MB. 
The best fix is probably reenabling production optimisations when we build the app, which I gather involves doing something like:-

> Let's go with this for now, but the first comment in the linked issue offers a good option: the `triggerObjective` could be an object with `name` and `implementation` properties. (We can also add some type safety on the implementation property)

_Originally posted by @andrewgordstewart in https://github.com/statechannels/monorepo/pull/1699#issuecomment-624339041_

**Comment by snario** [comment]
Fixed by #1743
