### ISSUE TITLE
Integration test actors should sign blockchain transactions according to selectedAddress

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1732]
Currently, all integration test actors sign all blockchain transactions from address `0xD9995BAE12FEe327256FFec1e3184d492bD94C31` (corresponds to [this private key)](https://github.com/statechannels/monorepo/blob/master/packages/devtools/src/constants.ts#L4). See https://github.com/statechannels/monorepo/issues/1577#issuecomment-625399027 for why this is bad.

This is true even if they have different `selectedAddress` values (which you can [set up](https://github.com/statechannels/monorepo/blob/master/packages/e2e-tests/puppeteer/helpers.ts#L133) if you are not using dappeteer)

I think if you _are_ using dappeteer, you just end up using address `0xD9995BAE12FEe327256FFec1e3184d492bD94C31` anyway.

So, this issue potentially requires code changes:
- [ ] Change [getProvider](https://github.com/statechannels/monorepo/blob/master/packages/xstate-wallet/src/utils/contract-utils.ts#L25) to use the right signer according to `window.eth.selectedAddress`
- [x] Change the dappeteer setup to use unique signinig keys

**Comment by geoknee** [comment]
When using a fake web3, it seems to me that we don't care about addresses at all, since we never interact with a chain. 

When using dappeteer, I was expecting this step to avoid this problem: 
https://github.com/statechannels/monorepo/blob/af9d16b0fda4f1379b7066bb24cacf0d1b60b5ea/packages/e2e-tests/puppeteer/helpers.ts#L198-L202

any idea why it does not?

**Comment by andrewgordstewart** [comment]
> When using a fake web3, it seems to me that we don't care about addresses at all, since we never interact with a chain.

If I set `USE_DAPPETEER=false`, then I _do_ set up a fake web3, but I _still_ interact with a chain during integration tests, right?

> When using dappeteer, I was expecting this step to avoid this problem:
> https://github.com/statechannels/monorepo/blob/af9d16b0fda4f1379b7066bb24cacf0d1b60b5ea/packages/e2e-tests/puppeteer/helpers.ts#L198-L202
> 
> any idea why it does not?

:+1: nice!

It looks like in the `seed-download` test, [unique private keys](https://github.com/statechannels/monorepo/blob/master/packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts#L44-L45) are indeed meant to be used. So, if this code is working as intended, we shouldn't see the nonce issue on circle, where dappeteer is used.

In the multiple-leecher test, the same address is used in [multiple browsers](https://github.com/statechannels/monorepo/blob/ags/multiple-leecher-test/packages/e2e-tests/puppeteer/__tests__/web3torrent/stress.test.ts#L60).

The `0` in this case was originally the argument for the `sloMo` argument, which is now the third argument instead of the second argument, post rebase-on-master. Since the types match, it's acceptable as the second argument. I guess this is a strike against non-named optional parameters!

**Comment by geoknee** [comment]
As far as the tests in the e2e package go,  the only way to interact with a chain at the moment is to use dappateer. It's the only true ethereum provider. Fake Web3 just mocks out the interface to an ethereum provider. It can't sign anything.

**Comment by andrewgordstewart** [comment]
> As far as the tests in the e2e package go, the only way to interact with a chain at the moment is to use dappateer. It's the only true ethereum provider. Fake Web3 just mocks out the interface to an ethereum provider. It can't sign anything.

I'm not sure if this matches my current experience, where it seems like actual deposits are made when I set `USE_DAPPETEER=false`.

When I look at the code that is run in the browser, it is this.

```
    window.web3 = new Web3("http://localhost:${ganachePort}");
    window.ethereum = window.web3.currentProvider;
    
    window.ethereum.enable = () => new Promise(r => {
      console.log("[puppeteer] window.ethereum.enable() was called");
      web3.eth.getAccounts().then(lst => {
        web3.eth.defaultAccount = lst[${ganacheAccountIndex}];
        console.log("Using address " + web3.eth.defaultAccount);
        window.ethereum.selectedAddress = web3.eth.defaultAccount;
        r([window.ethereum.selectedAddress]);
    });      
    });
    window.ethereum.networkVersion = 9001;
    window.ethereum.on = () => {};
```

`new Web3("http://localhost:${ganachePort}")` -- this is a real ethereum provider, isn't it?

**Comment by geoknee** [comment]
Yeah I think you are right. We probably shouldn't call the function `setupFakeWeb3` (my bad).

**Comment by andrewgordstewart** [comment]
I see, good point.

**Comment by andrewgordstewart** [comment]
When I use dappeteer, in _headful_ mode, the developer experience is pretty annoying -- I have to manually confirm some of the transactions, since metamask asks to confirm the transaction in a _pop-up_ window, not the second tab (which I think is what dappeteer controls)

Nevertheless, all the channels reliably _open_ ( 🎉) but they do not reliably _close_.

**Comment by geoknee** [comment]
Have you tried not doing anything manually? I was under the impression things would work just fine in that case, and this is what happens on circle anyway.

**Comment by andrewgordstewart** [comment]
Yes, it hangs, seemingly forever. When I click confirm, puppeteer continues.

I see similar behaviour with metamask regularly -- sometimes the confirmation happens in the current window, and sometimes it happens in a popup window.

**Comment by andrewgordstewart** [comment]
> Have you tried not doing anything manually? I was under the impression things would work just fine in that case, and this is what happens on circle anyway.

I started the tests, didn't touch my computer, and it's been on this screen for 2 minutes.

<img width="1680" alt="Screen Shot 2020-05-08 at 7 58 55 AM" src="https://user-images.githubusercontent.com/8432675/81418680-e5864c00-9101-11ea-83fc-442a6c973f99.png">
