### ISSUE TITLE
Leecher cannot download file from seeder twice

### ISSUE THREAD

**Issue by snario** [statechannels/monorepo#1735]
Seems like the scenario where I:

1. Start seeding as A
2. Download successfully as B
3. Reload page of B
4. Try to download as B again

Fails — B cannot connect to A (channel opens but you see Connecting UI)

Possibly because A has a record of having already served this file to B. That is my guess.

**Comment by snario** [comment]
> Possibly because A has a record of having already served this file to B. That is my guess.

I don't think this is true based on short inspection.

**Comment by andrewgordstewart** [comment]
This might be related: https://github.com/statechannels/monorepo/issues/1851#issuecomment-629274401

**Comment by spersico** [comment]
So, I've been playing around this issue. 
I've got a couple of logs of when I replicated this issue:
[seeder logs.log](https://github.com/statechannels/monorepo/files/4636323/seeder.logs.log)
[leecher logs.log](https://github.com/statechannels/monorepo/files/4636324/leecher.logs.log)

Some findings:
 - The seeder creates a new channel for the leecher (which is correct).
 - If the seeder reloads the page and re-seeds the torrent, the leecher goes back into the normal flow of downloading, so this might point to some data not being correctly cleaned up in the seeder side.
 - The seeder seems to behave correctly, one thing I suspected was that some data in web3torrent would be repeated, or something like that, but that doesn't seem to be the case.
 - The issue mainly that I see is that the leecher never even attempts to make a payment to the channel. Is there any other data that might be no longer valid that get's persisted outside the realm of web3torrent?.

**Comment by kerzhner** [comment]
One reason why leeching might be broken:
- web3torrent client maintains a `peerList[infoHash][peerId]` dictionary that contains every wire for a torrent.
- The keys of the dictionary are peer ids, aka the state channel participant id or signing address (I am not sure which one...)
- The peer id for a leecher remains constant across reloads. So the `peerList[infoHash][peerId]` will contain stale data when a reloaded leecher tries to connect to a seeder.

My proposal is to index the peerList dictionary on seeding channel id aka `peerList[infoHash][pseChannelId]`.

Thoughts? @spersico

**Comment by kerzhner** [comment]
Latest progress on this issue. To observe the behavior:
1. Seed a file with the seeder.
1. Leech the file successfully.
1. Reload the leecher.
1. Try to leech the file again.
1. Observe the deadlock.

Observe the following:
- The last xstate transition on the seeder is to _acquiringLock_ state in the _ledger-funding_ workflow.
- In the logs above, on the seeder, note that after the transition to _defundGuarantor: {ledgerUpdate: "supportState"}_ state in _virtual-defunding-as-leaf_ workflow, we see the warning of `utils.js:424 Warning: No implementation found for action type 'releaseLock'`.

Any insight from @lalexgap or @andrewgordstewart is appreciated!

**Comment by andrewgordstewart** [comment]
That should be pretty easy to fix!

I think this'll do: https://github.com/statechannels/monorepo/pull/1914

**Comment by kerzhner** [comment]
This issue is resolved by https://github.com/statechannels/monorepo/pull/1914
