### ISSUE TITLE
Production: browser logs

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1750]
At the moment, the logs are a mix of objects and pino log lines. All of the logs should be pino log lines that can be piped to `pino-pretty`
<img width="1254" alt="Screen Shot 2020-05-08 at 12 09 22 PM" src="https://user-images.githubusercontent.com/1062379/81440633-38bdc600-9125-11ea-8acf-1e6e60e18036.png">

**Comment by andrewgordstewart** [comment]
Update:
- Logs are now [objects](https://github.com/statechannels/monorepo/blob/master/.env.production-ropsten#L29) in production.
- Log events are added to a cache as a pino log line.
   - [web3torrent](https://github.com/statechannels/monorepo/blob/master/packages/web3torrent/src/logger.ts#L62-L84)
    - [wallet](https://github.com/statechannels/monorepo/blob/master/packages/xstate-wallet/src/logger.ts#L17-L40)
    - [channel-provider](https://github.com/statechannels/monorepo/blob/master/packages/channel-provider/src/logger.ts#L13-L36)
- Users/developers can download the cache by calling [`window.saveWeb3torrentLogs()`](https://github.com/statechannels/monorepo/blob/master/packages/web3torrent/src/logger.ts#L94)
