### ISSUE TITLE
Required integration test

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1782]
This test will need to pass for the github PRs to get merged.

**Comment by andrewgordstewart** [comment]
My opinion: Apply these guidelines to all integration tests
- If the tests passes 5 times in a row on circle, we make it required.
- If developers need to re-run failed tests, re-running it _should_ pass 80% of the time.
   - The integration tests are relatively quick to re-run, so this isn't the worst short-term rule
- If the developer re-runs the test a couple of times and it keeps failing with the same error, they probably broke it, so they should fix that error

**Comment by andrewgordstewart** [comment]
https://github.com/statechannels/monorepo/pull/1781

**Comment by andrewgordstewart** [comment]
Seems like this is closed by #1781 , which is now merged
