### ISSUE TITLE
Don't show closed channels (after some time?) on Web3Torrent UI

### ISSUE THREAD

**Issue by snario** [statechannels/monorepo#1817]
The UI can be unwieldy when you revisit it after having used it for a while.

<img width="1500" alt="Screen Shot 2020-05-12 at 18 51 18" src="https://user-images.githubusercontent.com/1933029/81817665-07fdd800-94fb-11ea-8713-75c21bbe11e8.png">

Maybe let's just not show channels from previous "sessions" (created before recent page load)?

**Comment by geoknee** [comment]
Via #2139
