### ISSUE TITLE
Downloadable pino log in production

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1824]

**Comment by andrewgordstewart** [comment]
This should be resolved by https://github.com/statechannels/monorepo/pull/1836, but I am unable to verify that it works in production: https://app.circleci.com/pipelines/github/statechannels/monorepo/6431/workflows/04ed0bfd-5d1c-4d88-80b7-d82970320659/jobs/27017

**Comment by andrewgordstewart** [comment]
https://github.com/statechannels/monorepo/pull/1836 works
