### ISSUE TITLE
"No domain defined for channel"

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1828]
I have no useful logs, since the logs I downloaded just contain javascript object handles

**Comment by snario** [comment]
Almost certainly related to #1792 and needs to be addressed by #1819

**Comment by geoknee** [comment]
Maybe people are already aware of this, but just in case: https://github.com/statechannels/monorepo/blob/0d71d5608c693b4ae10533283b3225ff7e638711/packages/xstate-wallet/src/channel-wallet.ts#L58-L64

**Comment by lalexgap** [comment]
@andrewgordstewart Have you seen this error recently? I think we can close it if not.
