### ISSUE TITLE
TypeError: Cannot read property 'serialize' of undefined

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1867]
https://app.circleci.com/pipelines/github/statechannels/monorepo/6467/workflows/5423dd8a-fa71-46c8-99b3-44d444858ae1/jobs/27247

```
 FAIL  puppeteer/__tests__/web3torrent/seed-download.test.ts (15.106s)
  Web3-Torrent Integration Tests
    ✕ allows peers to start torrenting (13282ms)
 
  ● Web3-Torrent Integration Tests › allows peers to start torrenting

    TypeError: Cannot read property 'serialize' of undefined
 ```

**Comment by kerzhner** [comment]
https://github.com/statechannels/monorepo/pull/1858 moves the line that triggers this error. This issue will become stale after that PR is merged.

However, it is concerning that we are seeing this error. In theory, this line should never trigger the error:
https://github.com/statechannels/monorepo/blob/8548712f367ff2821182b975408f9f0209fdf430/packages/web3torrent/src/library/web3torrent-lib.ts#L194
