### ISSUE TITLE
Torrent DONE log

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1874]
I would add in the [DONE listener](https://github.com/statechannels/monorepo/blob/693658ab9e55f3bb5208c5c6e6a43a6495f4ca36/packages/web3torrent/src/library/web3torrent-lib.ts#L401-L402) ( before closing the channels).
Something that logs the final channels status, and the amount paid to each wire, before closing it: I did this in local, for example:
```
log.info({torrent, channels: this.paymentChannelClient.channelCache}, '<< Torrent DONE!');
      torrent.wires.map(wire => {
        const {peerAccount, peerChannelId} = wire.paidStreamingExtension;
        const channelOfWire = this.paymentChannelClient.channelCache[peerChannelId];
        if (channelOfWire) {
          const balance = bigNumberify(channelOfWire.beneficiaryBalance).toString();
          log.info(`<< ${peerAccount} Final Balance: ${balance} Downloaded ${wire.downloaded}`);
        }
      });
```
This would give us a final status check:
![image](https://user-images.githubusercontent.com/10502605/82097498-6385bc80-96d9-11ea-8d76-f362575ba66d.png)

_Originally posted by @spersico in https://github.com/statechannels/monorepo/pull/1858#issuecomment-629496662_

**Comment by spersico** [comment]
closed by #1917
