### ISSUE TITLE
Duplicate JSONRPC requests

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1883]
> [Attempting to sign a stale state](https://app.circleci.com/pipelines/github/statechannels/monorepo/6569/workflows/70709aef-b443-4611-90cd-a70aeb7a8b03/jobs/28023/parallel-runs/0/steps/0-107) 👀

```
❯ grep UpdateChannel seed-download.pino.log | jq -c '{msg: .msg, id: .jsonRpcRequest.id, time: .time}' | pino-pretty | pbcopy

[1589673253282]: INCOMING JSONRPC REQUEST:
    id: 7
[1589673253361]: INCOMING JSONRPC REQUEST:
    id: 9
[1589673253381]: INCOMING JSONRPC REQUEST:
    id: 10
[1589673253447]: INCOMING JSONRPC REQUEST:
    id: 9
```

The channel client/provider is making the same request twice.

_Originally posted by @andrewgordstewart in https://github.com/statechannels/monorepo/pull/1882#issuecomment-629840861_

**Comment by snario** [comment]
@andrewgordstewart don't we expect duplicates since those logs are for 2 separate browsers?

**Comment by andrewgordstewart** [comment]
Good point
