### ISSUE TITLE
[e2e-tests] web3torrent logs are missing from pino.log

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1896]
An example run: https://27855-209829093-gh.circle-artifacts.com/0/tmp/seed-download.pino.log

**Comment by snario** [comment]
Fixed in #1893

**Comment by andrewgordstewart** [comment]
https://github.com/statechannels/monorepo/commit/28bd93f4c7a8ee788cddfbbf5fbbe3c7e2d5ea03 fixed the problem.
