### ISSUE TITLE
"Not your Turn" when canceling downloads

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1918]
**Describe the bug :bug:**
Testing manually (in master) using **virtual channels** while downloading a file the cancel button might not work on the first time it's clicked, showing instead an error in the console, telling me that it's not my turn.

Are the `closeChannel` channel updates ruled by the same rules than the other updates (that it must wait for its turn)? If it is, then the `PaymentChannelClient.closeChannel()` should wait for its turn, and only **then** close the channel, not throw an error, making the user click have no feedback at all.

This might be related to the error found in #1903, but it's an error by itself.

**Comment by andrewgordstewart** [comment]
https://github.com/statechannels/monorepo/pull/1871

**Comment by spersico** [comment]
> #1871

I see that George's PR is responsible for this behaviour. Is it the correct behaviour? What should be the approach to have a reliable cancel button, that is able to close channels?

**Comment by spersico** [comment]
> > #1871
> 
> I see that George's PR is responsible for this behaviour. Is it the correct behaviour? What should be the approach to have a reliable cancel button, that is able to close channels?

I think that it should wait 'till the user's turn, and then call closeChannel right?

**Comment by geoknee** [comment]
@spersico yes, we decided that it is the responsibility of the app to wait until it is our turn.  The wallet API specifies an error response if you try to close when not your turn. Apologies for not signalling this change more clearly !
