### ISSUE TITLE
Unable to reload web3torrent after switching networks

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1930]
1. Load web3torrent (either running locally or on production).
1. Switch networks in metamask. In my case, I am switching from local ganache to ropsten.
1. Try to reload the page. Spin infinitely.

**Comment by kerzhner** [comment]
4. Eventually see this.
<img width="1260" alt="Screen Shot 2020-05-20 at 11 32 26 AM" src="https://user-images.githubusercontent.com/1062379/82483691-a820a780-9a8d-11ea-924d-df858754a9ef.png">

**Comment by lalexgap** [comment]
@kerzhner has seen this across firefox and chrome.

**Comment by kerzhner** [comment]
I can reproduce this issue reliably running web3torrent locally. The web3torrent tab process CPU ramps up to 100% and stays at that level indefinitely
<img width="821" alt="Screen Shot 2020-05-29 at 3 12 39 PM" src="https://user-images.githubusercontent.com/1062379/83309739-eec57e80-a1be-11ea-8289-7a0a17d4394b.png">

**Comment by kerzhner** [comment]
The repro case is:
1. Run all services using `SC_ENV=virtual-funding`.
1. Load http://localhost:3000/ with Metamask pointed to local ganache.
1. Switch network to Ropsten.

**Comment by kerzhner** [comment]
Blocked on https://github.com/ethers-io/ethers.js/issues/861
