### ISSUE TITLE
ChannelsList is not filtered by the current torrent

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1949]
I think during recent refactoring we lost the data inside this component that is necessary to filter out irrelevant channels. This leads to a page that is polluted with all of my (historic) payment channels.

![Screenshot 2020-05-22 at 11 01 14](https://user-images.githubusercontent.com/1833419/82656367-8fde9300-9c1b-11ea-8cb0-63d3ac85114f.png)

I think we should not show these old channels, at least not on this screen. 

Perhaps they could be shown elsewhere ( [ Your Budget ] screen ? ) if they still need to be challenged.

We don't have much logic around handling *multiple* torrents at the same time in web3torrent. Although I think users can manually visit the correct URL to see info about each torrent. So I propose we filter on channels pertaining to the (single) current torrent that is being seeded or leeched. 

Reminder: a Torrent has many Wires. A wire has a single peer, and up to 2 channels with that peer.

**Comment by kerzhner** [comment]
Looks like this change is not as simple as I was initially hoping. At the moment, we display all channels in the channel cache. But, a channel in the channel cache does not reference the torrent that initiated the channel.

One alternative I considered is displaying all channels that correspond to existing wires for a torrent. I am not sure that would work for wires that have completed. And this approach would not show any channels for a torrent after a refresh.
