### ISSUE TITLE
Number of peers doesn't match

### ISSUE THREAD

**Issue by tomclose** [statechannels/monorepo#1973]
From Mike: this is because the number of peers is taken from webtorrent, and the peers in the table are taken from open channels.

Suggestion: get number of peers to just be a count of the rows in the table.

![Screen Shot 2020-05-26 at 5 23 30 PM](https://user-images.githubusercontent.com/29596/82925536-b97a2000-9f75-11ea-8f26-d2dfb1a47b00.png)

**Comment by geoknee** [comment]
Possible point of confusion since there can be 2 rows in their table for the same peer (one uploading, one downloading). 

One workaround is to iterate over the table rows and count the number of unique peers.
