### ISSUE TITLE
DexieError on Stress test

### ISSUE THREAD

**Issue by spersico** [statechannels/monorepo#1979]
**Describe the bug :bug:**
DexieError sometimes appear when running the stress test.

**Screenshot**
![dexieError](https://user-images.githubusercontent.com/10502605/82939091-30f58280-9f69-11ea-9a66-3974de0c381d.png)
**Downloaded Log**
[web3torrent.Tue, 26 May 2020 18_41_07 GMT.1385fed94.undefined.pino.log](https://github.com/statechannels/monorepo/files/4684413/web3torrent.Tue.26.May.2020.18_41_07.GMT.1385fed94.undefined.pino.log)

**Jest Console**
![image](https://user-images.githubusercontent.com/10502605/82939347-9ea1ae80-9f69-11ea-8754-e85cb11942a1.png)

**Comment by andrewgordstewart** [comment]
For reference, the logs, and the upper screenshot are missing the uncaught browser error that occurred _after_ this log statement:
```
[1590518367974] ERROR (xstate-wallet): Transaction error
    error: "Transaction committed too early. See http://bit.ly/2kdckMn"
    store: {
      "budgets": [],
      "channels": [],
      "ledgers": [],
      "nonces": [],
      "objectives": [],
      "privateKeys": [
        {
          "key": "0xbBbBE5f62A6C9B0642780e5B71Cc09794734f004",
          "value": "0x53b1bc4bf4bbfee9cb29f26511e0391bb772049fab8ffe8e980ed9407642e1b4"
        }
      ]
    }
    callback: "async () => {\n        var _privateKeys, _privateKeys2;\n\n        if (!((_privateKeys = privateKeys) === null || _privateKeys === void 0 ? void 0 : _privateKeys.length) && !(await this.getAddress())) {\n...}"
```

**Comment by spersico** [comment]
> For reference, the logs, and the upper screenshot are missing the uncaught browser error that occurred _after_ this log statement:
> 
> ```
> [1590518367974] ERROR (xstate-wallet): Transaction error
>     error: "Transaction committed too early. See http://bit.ly/2kdckMn"
>     store: {
>       "budgets": [],
>       "channels": [],
>       "ledgers": [],
>       "nonces": [],
>       "objectives": [],
>       "privateKeys": [
>         {
>           "key": "0xbBbBE5f62A6C9B0642780e5B71Cc09794734f004",
>           "value": "0x53b1bc4bf4bbfee9cb29f26511e0391bb772049fab8ffe8e980ed9407642e1b4"
>         }
>       ]
>     }
>     callback: "async () => {\n        var _privateKeys, _privateKeys2;\n\n        if (!((_privateKeys = privateKeys) === null || _privateKeys === void 0 ? void 0 : _privateKeys.length) && !(await this.getAddress())) {\n...}"
> ```
that is shown here
![image](https://user-images.githubusercontent.com/10502605/82939766-2e475d00-9f6a-11ea-863b-e229217b5558.png)
