### ISSUE TITLE
Stuck waiting for my transaction to be mined

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1995]
Starting with a clean IndexedDB, trying to leech a file, run locally with `SC_ENV=virtual-funding`. Metamask notification comes up showing a successful transaction.
<img width="1275" alt="Screen Shot 2020-05-27 at 11 46 33 AM" src="https://user-images.githubusercontent.com/1062379/83060077-c1869e00-a00f-11ea-8c19-03febfe3021d.png">
[web3torrent.Wed, 27 May 2020 18_42_39 GMT.43d68cc28.0xbded65888A0E0796545cB0EcfA2b91863A0c6E35.pino.log](https://github.com/statechannels/monorepo/files/4691052/web3torrent.Wed.27.May.2020.18_42_39.GMT.43d68cc28.0xbded65888A0E0796545cB0EcfA2b91863A0c6E35.pino.log)

**Comment by andrewgordstewart** [comment]
Just to be clear, this is reproduced by opening web3torrent by hand, and not by running an integration test?

**Comment by kerzhner** [comment]
> Just to be clear, this is reproduced by opening web3torrent by hand, and not by running an integration test?

Yes. Hub, wallet, and w3t are run with `SC_ENV=virtual-funding`. The seeder successfully uploads the file (and opens a channel with the hub).

**Comment by lalexgap** [comment]
I've been unable to repro this locally using `SC_ENV=virtual-funding`, putting this on the backburner for now and will investigate it if it pops up locally for me.

**Comment by lalexgap** [comment]
I ran into this locally and the event fired seems that there's too much ETH deposited:

```
assetHolder[0] event 
{time: 1590703004207, level: 30, module: "chain", event: {…}}
event:
address: "0x4ad3F07BEFDC54511449A1f553E36A653c82eA57"
args: Array(3)
0: "0xf863a8e375701d9a582ac6439cf0c78014b800890d3231c2a7db42c5e2988f7c"
1: BigNumber {_hex: "0x3b9aca00", _isBigNumber: true}
2: BigNumber {_hex: "0x77359400", _isBigNumber: true}
amountDeposited: BigNumber {_hex: "0x3b9aca00", _isBigNumber: true}
destination: "0xf863a8e375701d9a582ac6439cf0c78014b800890d3231c2a7db42c5e2988f7c"
destinationHoldings: BigNumber {_hex: "0x77359400", _isBigNumber: true}
length: 3
__proto__: Array(0)
blockHash: "0xc3d28f3ec84204e46c16a90a8ca033e24a78c1ee66da22accff930543c80f7b6"
blockNumber: 24
data: "0x000000000000000000000000000000000000000000000000000000003b9aca000000000000000000000000000000000000000000000000000000000077359400"
decode: ƒ (data, topics)
event: "Deposited"
eventSignature: "Deposited(bytes32,uint256,uint256)"
getBlock: ƒ ()
getTransaction: ƒ ()
getTransactionReceipt: ƒ ()
logIndex: 0
removeListener: ƒ ()
removed: false
topics: (2) ["0xb39477ecc06c5293391f8b73168b655d9c1310af93dbbf043187d79f881bbb8f", "0xf863a8e375701d9a582ac6439cf0c78014b800890d3231c2a7db42c5e2988f7c"]
transactionHash: "0xc78cb10c3734139f151790d3cdc8fe7ddc3de31cbc42f948d3425abb50a1ef10"
transactionIndex: 0
__proto__: Object
level: 30
module: "chain"
time: 1590703004207
__proto__: Object
```

**Comment by lalexgap** [comment]
Just reproduced this on production. It looks like the chainview query doesn't return the latest amount.
[trans-not-detected-web3torrent.Fri, 29 May 2020 16_26_48 GMT.50e77c3f8.0xa4988d69E40AFf5695C133952cac8A36606438dD.pino.log](https://github.com/statechannels/monorepo/files/4702991/trans-not-detected-web3torrent.Fri.29.May.2020.16_26_48.GMT.50e77c3f8.0xa4988d69E40AFf5695C133952cac8A36606438dD.pino.log)

**Comment by lalexgap** [comment]
The particular issue looks like the query to the chain returns a stale amount. The event from the `contract` gets fired and on the event we see a `destinationHolding` value of `0x77359400`

``` {"time":1590769395584,"level":30,"module":"chain","event":{"blockNumber":7993382,"blockHash":"0x98fc8a6d3ebfea7e687cfe9621a4d50d0cc45302fc6b649b45d3b48bb0d91fa7","transactionIndex":12,"removed":false,"address":"0x9aca3C3Eca5FD2D0D8De18D0F079FefdeBa837de","data":"0x000000000000000000000000000000000000000000000000000000003b9aca000000000000000000000000000000000000000000000000000000000077359400","topics":["0xb39477ecc06c5293391f8b73168b655d9c1310af93dbbf043187d79f881bbb8f","0xf19a0bc4165b6154d57f77bfeaba4a9482a7eebd85a5ecdddd5d14d64964e243"],"transactionHash":"0xb726da84d2f5466f65133b0072f65a8c39b063b392ad8ce07897f8c90f792b8b","logIndex":7,"event":"Deposited","eventSignature":"Deposited(bytes32,uint256,uint256)","args":["0xf19a0bc4165b6154d57f77bfeaba4a9482a7eebd85a5ecdddd5d14d64964e243",{"_hex":"0x3b9aca00","_isBigNumber":true},{"_hex":"0x77359400","_isBigNumber":true}]},"msg":"assetHolder[0] event","name":"xstate-wallet"}```

However the "chain view" query (which calls `await ethAssetHolder.holdings(channelId);`) is returning a holding amount of `0x3b9aca00`
```
{"time":1590769395960,"level":30,"module":"chain","amount":{"_hex":"0x3b9aca00","_isBigNumber":true},"channelStorage":{"turnNumRecord":{"_hex":"0x00","_isBigNumber":true},"finalizesAt":{"_hex":"0x00","_isBigNumber":true}},"finalized":false,"blockNum":{"_hex":"0x79f826","_isBigNumber":true},"msg":"Chain query result","name":"xstate-wallet"}
```

One possible issue is that we construct a new `Contract` when performing the chain query (see https://github.com/statechannels/monorepo/blob/b2aaa7dd3a6ccc4a0c4cf4688696674d982bcbd5/packages/xstate-wallet/src/chain.ts#L374). In theory I think that should work but there might be some caching issues under the covers.

I think the next steps are:
- Try using existing `Contracts` instead of constructing new ones
- Create an issue in the `ethers` repo to get feedback/insight.

**Comment by andrewgordstewart** [comment]
> ). In theory I think that should work but there might be some caching issues under the covers.
> I think the next steps are:
> 
> * Try using existing `Contracts` instead of constructing new ones
> * Create an issue in the `ethers` repo to get feedback/insight.

I believe that https://github.com/statechannels/monorepo/issues/2031 is another example of this.

The [failure](https://app.circleci.com/pipelines/github/statechannels/monorepo/7049/workflows/a10c5a11-176c-47a3-9d7d-479f26f88134/jobs/31828/steps) referenced there was at 17d737a37d6216014148a54a3808abd4b84175a4, which has 81ae979f8c374640b942181f304d5e6cedbd045e in its history.

If we can confirm that #2031 is a duplicate of this issue, then I think that rules out the "Using new contracts causes stale chain data"

A `BehaviourSubject` for the chain feed would be a better solution: you would still have to fetch the chain data once, to populate the initial value, but after that, the latest known chain data would always be available.

**Comment by lalexgap** [comment]
> I believe that #2031 is another example of this.
> 
> The failure referenced there was at 17d737a, which has 81ae979 in its history.
> 
> If we can confirm that #2031 is a duplicate of this issue, then I think that rules out the "Using new contracts causes stale chain data"

I've taken a quick look at the [logs](https://31828-209829093-gh.circle-artifacts.com/0/home/circleci/project/logs/multiple-leecher.pino.log) and one thing different from normal failures is that I don't see the `Deposited` event get logged out from the wallet [here](https://github.com/statechannels/monorepo/blob/3c5d73e601166c9b788ad970081c917e60c74e41/packages/xstate-wallet/src/chain.ts#L269)

In the error case I've seen we see the `Deposited` event fire but then the query to the chain seems to return a stale result.

> A `BehaviourSubject` for the chain feed would be a better solution: you would still have to fetch the chain data once, to populate the initial value, but after that, the latest known chain data would always be available.

I'm not sure that a `BehaviourSubject` would fix the case where the `Deposited` event fires but the chain query returns stale data.

We can probably avoid the "stale data" being returned from a query by simply relying on the data from the event instead of performing a query to the chain. That may not affect #2031 though.

**Comment by andrewgordstewart** [comment]
> > A `BehaviourSubject` for the chain feed would be a better solution: you would still have to fetch the chain data once, to populate the initial value, but after that, the latest known chain data would always be available.
> 
> I'm not sure that a `BehaviourSubject` would fix the case where the `Deposited` event fires but the chain query returns stale data.
> 
> We can probably avoid the "stale data" being returned from a query by simply relying on the data from the event instead of performing a query to the chain. That may not affect #2031 though.

Oh, I didn't realize that `chain.ts` doesn't get data from the events :(

**Comment by andrewgordstewart** [comment]
> > I believe that #2031 is another example of this.
> > The failure referenced there was at [17d737a](https://github.com/statechannels/monorepo/commit/17d737a37d6216014148a54a3808abd4b84175a4), which has [81ae979](https://github.com/statechannels/monorepo/commit/81ae979f8c374640b942181f304d5e6cedbd045e) in its history.
> > If we can confirm that #2031 is a duplicate of this issue, then I think that rules out the "Using new contracts causes stale chain data"
> 
> I've taken a quick look at the [logs](https://31828-209829093-gh.circle-artifacts.com/0/home/circleci/project/logs/multiple-leecher.pino.log) and one thing different from normal failures is that I don't see the `Deposited` event get logged out from the wallet [here](https://github.com/statechannels/monorepo/blob/3c5d73e601166c9b788ad970081c917e60c74e41/packages/xstate-wallet/src/chain.ts#L269)
> 
> In the error case I've seen we see the `Deposited` event fire but then the query to the chain seems to return a stale result.

I believe that the timestamps are relatively believable, since it's the same system time. So, maybe in this case
1. the deposit happened
2. then, the workflow started listening for deposits, starting with a `getChainInfo` call

and (2) happened after (1) -- meaning it didn't notice the deposited event -- but too soon after (1) -- meaning `getChainInfo` doesn't yet reflect the deposit.

**Comment by lalexgap** [comment]
> I believe that the timestamps are relatively believable, since it's the same system time. So, maybe in this case
> 
> 1. the deposit happened
> 2. then, the workflow started listening for deposits, starting with a `getChainInfo` call
> 
> and (2) happened after (1) -- meaning it didn't notice the deposited event -- but too soon after (1) -- meaning `getChainInfo` doesn't yet reflect the deposit.

One thing to note is that we've added logging for any assetHolder events that gets wired up when the chain is initialized (at start up). So we should always see a log entry for the `Deposited` event regardless of whether a workflow is using the feed or not.

So I'd still expect to see a `Deposited` event log entry which I don't see in the logs.

**Comment by andrewgordstewart** [comment]
Well, it's starting to look like https://github.com/statechannels/monorepo/issues/1803 is more urgent.

**Comment by tomclose** [comment]
@andrewgordstewart has a quickfix for this, where we re-query the chain after waiting a while. We should merge this for launch.
