### ISSUE TITLE
[wallet] AdjudicatorWatcher updates the adjudicator-state

### ISSUE THREAD

**Issue by tomclose** [statechannels/monorepo#20]
Update the adjudicator watcher to handle the new events emitted by the nitro contracts, and update the adjudicator-state accordingly. 

### Notes

The adjudicator watcher is responsible for subscribing to events from the provider, and triggering actions that are consumed by the adjudicator-state-reducer. The adjudicator-state-reducer updates the adjudicator-state, a cached version of the adjudicator state, restricted to channels of relevance to the wallet. The wallet declares the channels it is interested in via the [channel subscriptions](https://github.com/magmo/apps/blob/master/packages/wallet/src/redux/state.ts#L68) and the adjudicator-watcher should only trigger events for channels that appear in this list.

The adjudicator-state will need to be updated to the following format:
```ts
export interface AdjudicatorChannelState {
  channelId: string;
  balance: string; // leave for time being
  finalized: boolean; // see note below
  challenge?: Challenge;
  finalizesAt: string; // or bignumber ??
  outcomeBytes: string;
  challengerAddress: Address;
}
```
Note: we'll keep the `finalized` property, even though it's redundant information, to keep the current workflow with the `ChallengeWatcher`: the `ChallengeWatcher` will observe open challenges, and trigger an event when they timeout, which will flip this property to `true`. That way reducers (a) don't have to do time comparisons themselves, and (b) receive an action to initiate the next steps.

### Testing

The [current testing strategy](https://github.com/magmo/apps/blob/master/packages/wallet/src/contract-tests/adjudicator-events.test.ts) seems pretty good. It would be nice to hook the reducer in (as in the full example [here](https://github.com/wix/redux-saga-tester#full-example)), so that we can do a full integration tests of the form:

1. Trigger action on the contract.
2. Check to see that `adjudicator-state` is as expected.

We should add tests for all of the methods on the nitro-adjudicator. You'll probably want to import the nitro-test-contracts, so you can use [this approach](https://github.com/statechannels/nitro-protocol/blob/master/test/contracts/ForceMove/checkpoint.test.ts#L144) for putting the on-chain state in the right state before the test (if necessary).

### Scope
* We'll limit the scope to the public methods on the force-move contract: `force-move`, `respond`, `refute`, `checkpoint`, and `conclude`
* The `deposit` event is out of scope for this work, but will be covered later as part of the `AssetHolderWatcher` work.
* Any update to the states in channel store is out of scope for this work. We're only focussed on updates to the `adjudicator-state`. The work to pull in states from transaction will form part of later work.

### Acceptance criteria
This work is complete when an updated [adjudicator events test](https://github.com/magmo/apps/blob/master/packages/wallet/src/contract-tests/adjudicator-events.test.ts) passes.

**Comment by lalexgap** [comment]
I believe this is completed by #83.
