### ISSUE TITLE
Loads of zero byte disconnected channels

### ISSUE THREAD

**Issue by tomclose** [statechannels/monorepo#2003]
George and I ended in a state where:
* The original seeder (George chrome) had only 5 connections
* Tom's Brave and George's Opera managed to download the file successfully
* Tom's Chrome and Tom's Firefox were both stuck at 39MB/129MB
* And the two browsers that were stuck open channels, but no data is transferred.

![Screen Shot 2020-05-28 at 11 18 34 AM](https://user-images.githubusercontent.com/29596/83129698-19d3a380-a0d5-11ea-9452-607e686d6df2.png)

**Comment by tomclose** [comment]
Unexplained things:
* Even though there doesn't seem have been any data exchanged with the original seeder, there's still an active channel, that hasn't been killed by webtorrent

**Comment by tomclose** [comment]
The zero byte channels are stuck in the pre-fund setup state. Here's an example:

```
key: "0x0095c6fcd3c639d8f9cca26baedb79153298fd691c6d15da4ca1e7aa562e9c9e"
value:
applicationDomain: "web3torrent.statechannels.org"
channelConstants:
appDefinition: "0xde8585b18e89ad34521f87f236dd745b1c4af99b"
chainId: "3"
challengeDuration: "300"
channelNonce: "8"
participants: Array(2)
0: {participantId: "0x0E9f7295BFC5E1783B7629221ACa82BcdF25e0F8", signingAddress: "0x0E9f7295BFC5E1783B7629221ACa82BcdF25e0F8", destination: "0x00000000000000000000000087e0ED760fb316eeb94Bd9cF23D1d2BE87aCe3d8"}
1: {participantId: "0x675221673cE0bd41b351433991967D8DFd3B2622", signingAddress: "0x675221673cE0bd41b351433991967D8DFd3B2622", destination: "0x000000000000000000000000d4Fa489Eacc52BA59438993f37Be9fcC20090E39"}
length: 2
funding: undefined
myIndex: 1
stateVariables: Array(1)
0:
appData: "0x0000000000000000000000000000000000000000000000000000000000000000"
appDefinition: "0xde8585b18e89ad34521f87f236dd745b1c4af99b"
chainId: "3"
challengeDuration: {_hex: "0x012c", _isBigNumber: true}
channelNonce:
_hex: "0x08"
_isBigNumber: true
isFinal: false
outcome:
allocationItems: (2) [{…}, {…}]
assetHolderAddress: "0x9aca3C3Eca5FD2D0D8De18D0F079FefdeBa837de"
type: "SimpleAllocation"
participants: Array(2)
0:
destination: "0x00000000000000000000000087e0ED760fb316eeb94Bd9cF23D1d2BE87aCe3d8"
participantId: "0x0E9f7295BFC5E1783B7629221ACa82BcdF25e0F8"
signingAddress: "0x0E9f7295BFC5E1783B7629221ACa82BcdF25e0F8"
1: {participantId: "0x675221673cE0bd41b351433991967D8DFd3B2622", signingAddress: "0x675221673cE0bd41b351433991967D8DFd3B2622", destination: "0x000000000000000000000000d4Fa489Eacc52BA59438993f37Be9fcC20090E39"}
length: 2
signatures: Array(2)
0: {signature: "0xa176e0e83d4ce319c18288a4c754c08eccd1500fc180b5d3…117cc0200020b5d093351007910f18a06e0385143a3b6fa1c", signer: "0x0E9f7295BFC5E1783B7629221ACa82BcdF25e0F8"}
1: {signature: "0x9e128beca2579495aa0a6b6415632eeeb8eabfbfa3cc3b8e…531cb0876f8f2b57e32eb631b51c22064c4676d4f1b1ca11b", signer: "0x675221673cE0bd41b351433991967D8DFd3B2622"}
length: 2
stateHash: "0xd5bf99c05737f39c4c19892764766d58cf221005cd5742841ad07d8e8819863a"
turnNum: {_hex: "0x00", _isBigNumber: true}
length: 1

**Comment by tomclose** [comment]
The turnNum on the ledger channel is "0xc" = 12. I see 11 channels that have transactions, and 12 funded channels in the ledger channel outcome:
```
outcome:
allocationItems: Array(14)
0: {destination: "0x00000000000000000000000087e0ED760fb316eeb94Bd9cF23D1d2BE87aCe3d8", amount: {…}}
1: {destination: "0x000000000000000000000000d4Fa489Eacc52BA59438993f37Be9fcC20090E39", amount: {…}}
2: {destination: "0xfc1f0930d414f7766d70d2005e41403906023a8e8c17fbb1a4a6cba258c2f609", amount: {…}}
3: {destination: "0x390aa43e53a8f1f2b2656fe7053f6e728907159f68addae4f43c3f18df20c80e", amount: {…}}
4: {destination: "0xb2748948a249bea0ed50ef32ac467a64ec4e443909cd6af12d3537fbbbc89fdf", amount: {…}}
5: {destination: "0x1e19a4209e76516af79eea61f3a55ad8b560a1572ce4b0a36e7efb8093d433a9", amount: {…}}
6: {destination: "0x94517ec0140702f77fd473e5e76b9b9ccfbb8f50306799f3c93f7e645a316d35", amount: {…}}
7: {destination: "0x64541f7d14a2a37321eee492adc20baa2a540073defedaadd1f0581088993f86", amount: {…}}
8: {destination: "0x273f0b887a4241106d90e0d7bb5e7d93df2b03eb1fd3855b2df72bc9b1176869", amount: {…}}
9: {destination: "0x808d8ffcde9e8f889197149de91f2f4df1829814598150481b8b82ec7c80ce31", amount: {…}}
10: {destination: "0x30fa419ac78184151860904bd376112b60700af09a8d3e8ff2ca62cfff01ef38", amount: {…}}
11: {destination: "0xa1a9ef09e35d14dc0f83183604322a6cc29b3f1322fa0814c71ea0759968dbd4", amount: {…}}
12: {destination: "0x0d72316e5c9fd1c5c28ddaf89aec640c0c729a921cf3c26a8afff5ad6f21b53b", amount: {…}}
13: {destination: "0x2a25d68a3150686a33485af98e3cd7738f18b4d0c039121c964a2db8d41d4d2a", amount: {…}}
```

**Comment by andrewgordstewart** [comment]
@tomclose Do you have either reproduction instructions or logs associated with this issue?

**Comment by lalexgap** [comment]
I'm finding this one difficult to reproduce reliably. I managed to get it happen once with 4 browsers but it only seemed to happen once. Will continue to dig into this.

**Comment by andrewgordstewart** [comment]
> I'm finding this one difficult to reproduce reliably. I managed to get it happen once with 4 browsers but it only seemed to happen once. Will continue to dig into this.

How did you reproduce it?

**Comment by lalexgap** [comment]
@andrewgordstewart Using the production site I just had one browser seed a large file and the three other. browsers download.

**Comment by andrewgordstewart** [comment]
Have you tried doing the same with the multiple leecher test?

**Comment by tomclose** [comment]
Why are they disconnected (even after Liam's fix)? The channel stalls in `turnNum = 0`, which seems to cause both players to stall, thinking it's the other player's turn.

**Comment by tomclose** [comment]
Debugging with [these logs](https://github.com/statechannels/monorepo/files/4701932/web3torrent.09521cb38.0xF7934633D558591BDEc487804879fD4bbDDfD3B4.pino.log).

* `0x135d17ec6514660cc28834c591ba3685ac2728f4d34a9e17a736528d33b953b4` is an app channel with a double signed state 0.
* We try to fund that channel using the workflow `JOIN_CHANNEL-0x135d17ec6514660cc28834c591ba3685ac2728f4d34a9e17a736528d33b953b4/create-and-fund/workflow`
* We don't see anything after we transition to `"workflow":"ledger-funding","to":"acquiringLock"`

In the log file, there are 4 transitions `to: 'acquiringLock'`, and only one transition `from: 'acquiringLock'`.

**Comment by snario** [comment]
Seems like if the hub fails to respond, or the wallet fails to acknowledge a message for some reason, that one channel waiting for a supporting state from the hub could basically infinitely hold the lock preventing all future channels from being funded.

**Comment by tomclose** [comment]
The first time the lock is acquired it is for `JOIN_CHANNEL-0x8b619c7cd67b652c3c900731ca267fb2681338c6db466a6e85aad1a9c1f7edd9/create-and-fund/workflow/ledger-funding`. Looking in the store I see that channel `0x8b6...` is still at the pre-fund-setup (double-signed state 0), which probably means that funding didn't complete.

**Comment by snario** [comment]
1. Channel `0xb1e` is the target when the lock is first acquired (and never released)
2. The hub sends, and the wallet received, signed state with turnNum 0 for `0xb1e`
3. It [looks like](https://github.com/statechannels/monorepo/blob/77570c371c1a352d21685e5e5c2ffb812fce2264/packages/xstate-wallet/src/workflows/ledger-funding.ts#L101-L102) the wallet is expecting turnNum 1

**Comment by tomclose** [comment]
The last time there's any activity on that workflow is when it transitions from `checkingTarget` to `{"fundingTarget":"getTargetOutcome"}`.

Does that mean that the `getTargetOutcome` function didn't complete? It looks like it just fetches ledger channel data from the store, and then updates the outcome to allocate to the `targetChannelId`. There are a couple of errors that could be thrown, but I would've thought I'd see them in the logs?

**Comment by snario** [comment]
Possibly the transition to `#ledger-funding.failure` is not happening as expected?

```diff
diff --git i/packages/xstate-wallet/src/workflows/ledger-funding.ts w/packages/xstate-wallet/src/workflows/ledger-funding.ts
index 663cbfec6..df1113c26 100644
--- i/packages/xstate-wallet/src/workflows/ledger-funding.ts
+++ w/packages/xstate-wallet/src/workflows/ledger-funding.ts
@@ -118,7 +118,7 @@ const services = (store: Store): Record<Services, ServiceConfig<Init>> => ({
 });
 
 const actions = {
-  escalateError: escalate(({error}) => ({type: 'FAILURE', error})),
+  escalateError: escalate(({error}) => ({type: FAILURE, error})),
   releaseLock: (ctx: WithLock) => ctx.lock.release()
 };
 ```

**Comment by snario** [comment]
Could an error be getting suppressed? I'm trying to follow the logic, seems like `"FAILURE"` gets sent to the parent machine (i.e., `create-and-fund`) but I see no code that handles that transition

**Comment by tomclose** [comment]
After the workflow `JOIN_CHANNEL-0x8b619c7cd67b652c3c900731ca267fb2681338c6db466a6e85aad1a9c1f7edd9` transitions to `getTargetOutcome` a push message comes in at time `1590756754560`. The push message is a state update from `0x2A2ACc5FEe83d01Cb46C060f2FB86b94DC59b649`, on a channel with 3 participants, updating the outcome at `turnNum: 1` to fund `0x8bd`.

This appears to be the update to `J` sent by the other participant.

**Comment by tomclose** [comment]
The next time the ledger channel id, `0x9e845d85e`, is mentioned after the first lock was acquired at `1590756754143`, is at `1590756754129` when we next acquire the lock at `1590756754129`.

**Comment by tomclose** [comment]
Interestingly I don't have the ledger channel `0x9e845` in my channel store. This could be a red-herring, as I vaguely remember looking at it earlier, and could easily have mistakenly deleted it.

**Comment by tomclose** [comment]
I've managed to recreate the symptoms of the issue, but the logs look pretty different.

To recreate I:
1. started web3torrent running in 3 browsers locally
2. uploaded a large file to one of them
3. tried cancelling and restarting a lot in one of the tabs
4. tried closing and reopening the seeder
5. eventually it happened.

Unfortunately the log download doesn't work in firefox, and the console is basically locked, but this is what I see:

![Screen Shot 2020-05-29 at 4 16 09 PM](https://user-images.githubusercontent.com/29596/83276140-14a35100-a1c8-11ea-927a-6a0e3bf24d99.png)

It appears to get stuck because there are insufficient funds in the budget. This actually makes sense. The budget says it has both spend and receive of `0x05d10d0d` but channels require `0x07b41298`. I guess if you open and close a lot of channels you use up your budget pretty quickly.

Lack of funds fits with the error I saw before, as `getTargetOutcome` has some checks that the ledger has enough money in it.

Is it possible that be refreshing I've reset the budget somehow, so that in one case I hit the problem at the budget level, and in the next case I hit it at the ledger level?

**Comment by tomclose** [comment]
This would also be consistent with what we saw yesterday: that the problem didn't manifest until quite a way through a large file, when we'd seen a lot of random disconnects, which would have eaten up the funds.

**Comment by tomclose** [comment]
Working hypothesis: you get this error when one of the participants doesn't have enough funds to open a channel, and the wallet/app doesn't handle it well.

**Comment by kerzhner** [comment]
Here is an issue that contains leecher, seeder, and hub logs for this scenario: https://github.com/statechannels/monorepo/issues/2025. The issue also contains IndexedDB data.

**Comment by tomclose** [comment]
Straight out of the gate:

![Screen Shot 2020-05-29 at 5 30 11 PM](https://user-images.githubusercontent.com/29596/83282825-11ad5e00-a1d2-11ea-9a6f-4b8312122113.png)

[web3torrent.Fri, 29 May 2020 16_29_40 GMT.50e77c3f8.0xaEB31f4E0267Dd7B48FFaA221756581395c8A764.pino.log](https://github.com/statechannels/monorepo/files/4703000/web3torrent.Fri.29.May.2020.16_29_40.GMT.50e77c3f8.0xaEB31f4E0267Dd7B48FFaA221756581395c8A764.pino.log)

The first channel here ^ is `0xe9b2c16905a6c8b2fe791ed6921936bb9f7066041ba10ae0cd48e683429ab693`. In the store, that channel is on turn 0. In the logs, the last thing I see is a `pushMessage` at `1590769636424`, which is a `J` update with two signatures, from the hub. This is in response to a my `messageQueued` that I sent to the hub at `1590769636172`. (I am `0xaEB31f`)

**For the first channel, I wasn't at fault - the first participant (`0x04bEA`) is. They didn't sign the joint channel update, presumably because they didn't complete ledger funding.**

**Comment by tomclose** [comment]
The second time, the same thing happened - this time with participant `0xa03a9a0935`.

Hypothesis: the file is large, and I was a bit late starting. This meant that everyone had already used up their budget, so there was no-one I could connect to.
