### ISSUE TITLE
Artifacts are not uploaded in optional integration tests

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#2021]
There should be screenshots and logs.

https://app.circleci.com/pipelines/github/statechannels/monorepo/7010/workflows/37dd7d04-5577-42b5-901c-2aaa234d8cbd/jobs/31511/artifacts

**Comment by snario** [comment]
Seemed to work here: https://app.circleci.com/pipelines/github/statechannels/monorepo/7021/workflows/56f6535d-c492-4b7e-91ae-ebd043dd2f3b/jobs/31615/artifacts
