### ISSUE TITLE
Metamask not detected on Brave/Opera

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#2023]
When using Brave/Opera I get the Metamask not installed banner even though I have metamask installed.

![image](https://user-images.githubusercontent.com/1620336/83279918-b310c180-a18a-11ea-9dca-9c0e545ade22.png)

**Comment by lalexgap** [comment]
It seems that @tomclose and @geoknee have been able to use to brave/opera so it looks like this is something particular to me?

**Comment by kerzhner** [comment]
I am also hitting this issue with Brave. So I don't think it's just your local setup @lalexgap.

**Comment by lalexgap** [comment]
@kerzhner with Brave I followed these [instructions](https://metamask.zendesk.com/hc/en-us/articles/360038596792-Issues-using-Metamask-in-Brave-browser) and was able to use metamask after.

**Comment by kerzhner** [comment]
I think maybe the Brave settings have changed, but I had different UI in my settings.
<img width="737" alt="Screen Shot 2020-06-03 at 1 17 05 PM" src="https://user-images.githubusercontent.com/1062379/83685078-e6918880-a59c-11ea-8fd8-8daf56102016.png">

But now, Metamask is detected properly on `web3torrent.statechannels.org`.
