### ISSUE TITLE
[web3torrent] Add additional UI to show ledger funds that are "locked" in app channels

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#2026]
Currently this UI reacts to an aggregate of funds over all payment channels : 

https://github.com/statechannels/monorepo/blob/50e77c3f81b64466584b012081bbc05baf9af5cf/packages/web3torrent/src/components/domain-budget-table/DomainBudgetTable.tsx#L43-L53
 
Spent/received are the numerators, spendBudget and recieveBudget are the denominators, and the ratio controls the position of our little speedometers: 

![Screenshot 2020-05-29 at 18 08 35](https://user-images.githubusercontent.com/1833419/83286200-6c958400-a1d7-11ea-852d-2bb8d6823427.png)

To me the idea of a budget a sort of license granted to wallet by the user, to sign off on changes to channels without prompting via the UI. Those changes in this instance are to my balance in any payment channel managed by web3torrent. I think the UI is doing a reasonable job of reflecting this.

If I run out of budget. Nothing super bad should happen. I just get another prompt from the wallet and increase my budget if I want to. No transactions necessary to recover from that.

I think there is also a need to also display information about the ledger channel with the hub, which is the funding source for all of these channels. It is one step higher in the funding tree, and is not covered by a budget, in the sense that we prompt the user when funding the ledger channel, and we also do not refer to any budget when allocating money from the ledger channel to a w3t payment channel. 

I would suggest that we want an *additional* component to show the following quantities of interest that relate to the ledger channel, namely: 

i) the amount allocated to Me
ii) the amount allocated to the Hub
iii) the sum of the amounts allocated to Payment channels.
iv) the amount I deposited on chain
v) the amount the hub has deposited on chain

If I run out of money in the ledger channel, this either requires a ledger channel top up or defunding of some running payment channels. 

This mockup is one way we could do it:
![Screenshot 2020-05-29 at 18 57 54](https://user-images.githubusercontent.com/1833419/83290287-517a4280-a1de-11ea-9630-eec5369be725.png)

A pot for me, a pot for the hub, and a pot for the payment channels which is divided into money that I should be able to get back into my pot, and money that my counterparties want to get back in their pot (which on my screen would go back into the hub's pot). Some of that (red gray, green gray) might need a challenge to recover.

Overall I think we should move towards thinking of budgets and ledger channels as fairly well independent of each other: up to now I think we have sometimes been using the terms interchangeably. 

But curious to know what others think.

**Comment by snario** [comment]
I liked Tom's idea:

```
|___<received budget_allocated>___________<locked>________<send budget_allocated>|
```

**Comment by geoknee** [comment]
>  Those changes in this instance are to my balance in any payment channel managed by web3torrent. 


I think maybe I'm wrong here. We already had the pattern of allowing the application to update app channels without prompt. I guess the budget is actually meant to cover *funding* new channels without prompt?

**Comment by geoknee** [comment]
Via #2034
