### ISSUE TITLE
[xstate-wallet] Budget Notifications never sent

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#2033]
As far as I can tell, we never call this function in the wallet:

https://github.com/statechannels/monorepo/blob/3c5d73e601166c9b788ad970081c917e60c74e41/packages/xstate-wallet/src/messaging.ts#L103-L110

Which means the app cannot display up to date information about the budget, since it currently expects these notifications so it can cache the budget in the payment-channel-client. 

I wasn't quite sure exactly where we should send this notification: in the application workflow? in the store?

**Comment by geoknee** [comment]
@lalexgap Do you have thoughts?

**Comment by lalexgap** [comment]
> @lalexgap Do you have thoughts?

I think we could create some `budget` related services or actions that we trigger from the workflow that 
- call the budget method in the `store` (aka `reserveFunds`)
- Sends out a budget notification 

I think this would follow a similar pattern that we use for `UpdateChannel` in the application workflow (https://github.com/statechannels/monorepo/blob/3c5d73e601166c9b788ad970081c917e60c74e41/packages/xstate-wallet/src/workflows/application.ts#L322)

It might make sense to create these in `workflow-utils` so we can share them between the `application` and `approve-budget` workflows.
