### ISSUE TITLE
Withdrawing doesn't work unless you refresh the page

### ISSUE THREAD

**Issue by tomclose** [statechannels/monorepo#2040]
1. Upload / download a file
2. Click withdraw, or cancel then withdraw (if you're downloading)
3. Wallet pops up, asks you to sign transaction in metamask. No transaction in metamask
4. Refresh the page
5. Click withdraw again
6. Then the transaction is in metamask

Liam, George and I all witnessed this behaviour in our test this afternoon.

**Comment by geoknee** [comment]
Haven't seen this issue recently.
