### ISSUE TITLE
[web3torrent] Error in DomainBudgetTable

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#2042]
I couldn't see my budget while leeching. So I clicked on 'My Budget'. I got this error:

`Cannot convert undefined  or null to object` in `DomainBudgetTable.tsx`. 

![Screenshot 2020-06-01 at 13 46 30](https://user-images.githubusercontent.com/1833419/83411263-cd0f0600-a40f-11ea-88b3-6fd92a8a81b5.png)

The app kept functioning (lots of logs in the console), but the UI completely disappeared.

**Comment by andrewgordstewart** [comment]
Can you upload the logs?

**Comment by geoknee** [comment]
I haven't seen this problem since merging #2034. Let's reopen if we see it again.
