### ISSUE TITLE
Reduce logging to sane levels

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#2057]

**Comment by andrewgordstewart** [comment]
A quick win would be to `log.trace` the workflow context in wallet transitions

**Comment by kerzhner** [comment]
It would also be nice to keep the logging level at trace in production for now. This way we have as much debugging information as possible for digging into issues.

**Comment by andrewgordstewart** [comment]
> It would also be nice to keep the logging level at trace in production for now. This way we have as much debugging information as possible for digging into issues.

We can
- save `trace` logs in the LogBlob (so it's downloadable)
- don't print `trace` logs to the console (so it doesn't overwhelm the console logs)

that doesn't save any memory, and doesn't lose any logs, just cleans up visual clutter.

**Comment by andrewgordstewart** [comment]
Another quick win: https://github.com/statechannels/monorepo/issues/2041#issuecomment-637737955

**Comment by andrewgordstewart** [comment]
I took a peek through https://32582-209829093-gh.circle-artifacts.com/0/home/circleci/project/logs/multiple-leecher.A.7.pino.log, which serializes a bunch of the web3torrent stuff away. 

Sorting the biggest file (~2MB) by line length, grabbing the first ~10% (150) lines, and reading the log message:
```
❯ cat multiple-leecher.A.7.pino.log | awk '{ print length(), $0 | "sort -n" }' | tail -n 150 | sed 's/^[0-9]* //' | jq .msg  
"<< unblockPeer: start"
"<< blockPeer"
"<< unblockPeer: finish"
"<< blockPeer"
"<< unblockPeer: finish"
"<< blockPeer"
"<< blockPeer"
"<< unblockPeer: start"
"<< unblockPeer: start"
"<< unblockPeer: finish"
"<< blockPeer"
"<< blockPeer"
"<< blockPeer"
"<< unblockPeer: finish"
"<< unblockPeer: finish"
"<< blockPeer"
...
```

So, to trim the logs size, we'll need to trim those log statements...

That being said ... why are peers blocked and unblocked so frequently? Does that affect torrent performance?

**Comment by andrewgordstewart** [comment]
> So, to trim the logs size, we'll need to trim those log statements...

For the record:
```
~/Downloads via ☕ v11.0.2 on ☁️  us-west-1 
❯ cat multiple-leecher.A.7.pino.log | awk '{ print length(), $0 | "sort -n" }' | tail -n 150 > longLines.log 

~/Downloads via ☕ v11.0.2 on ☁️  us-west-1 
❯ du -sh multiple-leecher.A.7.pino.log longLines.log                                                        
1.6M    multiple-leecher.A.7.pino.log
856K    longLines.log
```

The longest ~10% of lines consumed half the log space

**Comment by kerzhner** [comment]
The seeder blocks the leecher whenever the leecher has not prepaid for a piece. The leecher prepays for 4 pieces at a time. A piece is usually a small part of the overall torrent. With this scheme, we see block and unblock `torrent size/ (piece size * 4)` number of times.
