### ISSUE TITLE
Add faq

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#2069]
- [ ]  There should be a FAQ section somewhere which explains briefly, with links to relevant documentation or blog posts, the following things:
    - How Web3Torrent Works ([whimsical.com/Sq6whAwa8aTjbwMRJc7vPU](https://whimsical.com/Sq6whAwa8aTjbwMRJc7vPU))
    - What a state channel is
    - How the states are encoded into the bittorrent protocol for messaging
    - What a budget is and why we need it to protect the wallet
    - How the application communicates to the wallet, briefly (i.e., the API)
    - Something about how there is a hub running in the background

    NOTE: This should be *in addition* to the blog post about these things, as many people will not read the blog post and will instead just rely on whatever shows up on their web browser when they navigate to web3torrent.statechannels.org

**Comment by geoknee** [comment]
One idea I had for this is to sprinkle some ( ? ) buttons in well-chosen places in our UI. Clicking on these takes the user to the relevant anchor on the FAQ page (opens in new tab).

**Comment by geoknee** [comment]
https://www.notion.so/web3Torrent-FAQ-9f384d9dbadc4828aa81e14fcc360466

**Comment by geoknee** [comment]
The FAQ is currently a notion document. We can add a link in the web3torrent app.
