### ISSUE TITLE
Speed up web3torrent downloads

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#2099]

**Comment by andrewgordstewart** [comment]
I think that the primary issue is web3torrent rending as much as the GPU allows.

When I rate limit to 10 FPS, I can download at ~3MB/s locally

![downloading](https://user-images.githubusercontent.com/8432675/83927539-10d07b00-a742-11ea-9d0d-5ff8b12a39ab.gif)

A secondary issue could  be that the leecher blocks the seeder every 4th request.
