### ISSUE TITLE
Safari disallows access to IndexedDB through iFrames by default

### ISSUE THREAD

**Issue by snario** [statechannels/monorepo#2111]
I think I've uncovered an issue we're hitting. On Sentry, we see [this issue](https://sentry.io/organizations/statechannels/issues/1666677284/?project=5236239&query=is%3Aunresolved&statsPeriod=14d) quite a bit:

> **OpenFailedError** promiseReactionJob([native code])
> SecurityError IDBFactory.open() called in an invalid security context

It seems like Safari dislikes usage of IndexedDB within iFrames. Here is an issue: https://github.com/dfahlander/Dexie.js/issues/565

We could use localStorage as a backup.

![image](https://user-images.githubusercontent.com/1933029/84150901-88e3bd00-aa30-11ea-9ff3-231d9cf3430d.png)

**Comment by geoknee** [comment]
Thanks for flagging this. Re: a 'fix': I think we don't support safari for a number of reasons: no webTorrent support and no metamask. The rimble banner should catch safari users and point them to a browser that we do support. 

So I'll close unless there is something you think we should action.
