### ISSUE TITLE
Unable to leech from persistent seeder and some peers

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#2152]
![magmo-debug-June11](https://user-images.githubusercontent.com/1062379/84437109-4dd8b980-abe9-11ea-9a73-84f8be910c01.JPG)

[web3torrent.Thu, 11 Jun 2020 20_26_16 GMT.cfb2fabdf.0xfcef1fB3725BeED181dC2a415cA5e30B7C96832d.pino.log](https://github.com/statechannels/monorepo/files/4767205/web3torrent.Thu.11.Jun.2020.20_26_16.GMT.cfb2fabdf.0xfcef1fB3725BeED181dC2a415cA5e30B7C96832d.pino.log)

**Comment by kerzhner** [comment]
Reported by Joseph during a demo session.

**Comment by andrewgordstewart** [comment]
Who is the peer in the above screenshot? Do we have their logs?

**Comment by kerzhner** [comment]
The peer in the screenshot is the leecher (Joseph) downloading from the persistent seeder. We don't have the logs from the breakdown in leeching between this leecher (Joseph) and another seeder (Tom). But it sounds like it's reproducible scenario between Tom and Joseph, so we can likely get those logs.

A strange symptom is that Joseph was able to leech from me and Robert.

**Comment by kerzhner** [comment]
I dug into the log. The log appears to be for a seeder. The screenshot shows a leecher. This issue is no longer actionable. We'll need Joseph to reproduce the issue and grab logs again.
