### ISSUE TITLE
Persistent seeder is broken after migration to Goerli

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#2166]
<img width="1256" alt="Screen Shot 2020-06-12 at 1 20 25 PM" src="https://user-images.githubusercontent.com/1062379/84543082-85aa3480-acaf-11ea-9908-0ebe8f54c61b.png">

**Comment by lalexgap** [comment]
This was working at one point this morning.

 I did notice that we have two dynos going which both use the same address (which we saw cause issues when we did our standup demo). I'm now trying reducing it the one dyno to see if that fixes things.

**Comment by lalexgap** [comment]
> This was working at one point this morning.
> 
> I did notice that we have two dynos going which both use the same address (which we saw cause issues when we did our standup demo). I'm now trying reducing it the one dyno to see if that fixes things.

After reducing the dynos and restarting I was able to successfully download from the persistent seeder.

**Comment by lalexgap** [comment]
Closing for now but will re-open if we run into more issues with the seeder.
