### ISSUE TITLE
Cancel button fails: `Error: CloseChannel failed 5 in a row.`

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#2169]
While investigating solutions for https://github.com/statechannels/monorepo/issues/2135, I re-enabled the test where a leecher cancels the download in the integration test. 
[multiple-leecher.C.1.browser.log](https://github.com/statechannels/monorepo/files/4775675/multiple-leecher.C.1.browser.log)

[multiple-leecher.C.1.pino.log](https://github.com/statechannels/monorepo/files/4775674/multiple-leecher.C.1.pino.log)

Here is a screenshot before the page crashed:

![multiple-leecher C](https://user-images.githubusercontent.com/8432675/84581499-8d90d400-ad96-11ea-8f51-dec677758c7f.png)

Produced on d7828c3:

```
SC_ENV=circle-integration-w3t-with-hub yarn  start-servers web3torrent
SC_ENV=circle-integration-w3t-with-hub yarn test multiple
```

**Comment by tomclose** [comment]
Hopefully fixed by https://github.com/statechannels/monorepo/pull/2212
