### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#2178]
https://app.circleci.com/pipelines/github/statechannels/monorepo/7376/workflows/b9f0bd56-a7a7-4d9a-b819-da54fc19be29/jobs/34218

**Comment by kerzhner** [comment]
One failure https://app.circleci.com/pipelines/github/statechannels/monorepo/7408/workflows/6d21241a-53bc-4ad5-9afb-e4c2f064a6fd/jobs/34498:
```
@statechannels/web3torrent: FAIL src/library/client-seeding.test.ts (34.999s)
@statechannels/web3torrent:   ● Seeding and Leeching › should perform the extended handshake between seeder and leecher
@statechannels/web3torrent:     : Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Error:
@statechannels/web3torrent:       67 |   });
@statechannels/web3torrent:       68 | 
@statechannels/web3torrent:     > 69 |   it('should perform the extended handshake between seeder and leecher', done => {
@statechannels/web3torrent:          |   ^
@statechannels/web3torrent:       70 |     seeder.seed(defaultFile as File, defaultSeedingOptions(), seededTorrent => {
@statechannels/web3torrent:       71 |       leecherA.add(seededTorrent.magnetURI, {store: MemoryChunkStore}, () => {
@statechannels/web3torrent:       72 |         expect(leecherA.torrents.length).toEqual(1);
@statechannels/web3torrent:       at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
@statechannels/web3torrent:       at Suite.Object.<anonymous>.describe (src/library/client-seeding.test.ts:69:3)
@statechannels/web3torrent:       at Object.<anonymous> (src/library/client-seeding.test.ts:27:1)
 ```

**Comment by kerzhner** [comment]
Another failure https://app.circleci.com/pipelines/github/statechannels/monorepo/7412/workflows/e114e689-14b3-4b7e-a5c5-fbd26ee30060/jobs/34522:
```
@statechannels/nitro-protocol: Error: timeout
@statechannels/nitro-protocol:     at Timeout.timeoutFunc (/home/circleci/project/node_modules/tcp-port-used/index.js:204:25)
 
@statechannels/nitro-protocol:     at ontimeout (timers.js:436:11)
@statechannels/nitro-protocol:     at tryOnTimeout (timers.js:300:5)
@statechannels/nitro-protocol:     at listOnTimeout (timers.js:263:5)
@statechannels/nitro-protocol:     at Timer.processTimers (timers.js:223:10)
@statechannels/nitro-protocol: error Command failed with exit code 1.
```

**Comment by lalexgap** [comment]
> Another failure https://app.circleci.com/pipelines/github/statechannels/monorepo/7412/workflows/e114e689-14b3-4b7e-a5c5-fbd26ee30060/jobs/34522:
> 
> ```
> @statechannels/nitro-protocol: Error: timeout
> @statechannels/nitro-protocol:     at Timeout.timeoutFunc (/home/circleci/project/node_modules/tcp-port-used/index.js:204:25)
>  
> @statechannels/nitro-protocol:     at ontimeout (timers.js:436:11)
> @statechannels/nitro-protocol:     at tryOnTimeout (timers.js:300:5)
> @statechannels/nitro-protocol:     at listOnTimeout (timers.js:263:5)
> @statechannels/nitro-protocol:     at Timer.processTimers (timers.js:223:10)
> @statechannels/nitro-protocol: error Command failed with exit code 1.
> ```

This failure looks like it's due to `server.ready` timing out [here](https://github.com/statechannels/monorepo/blob/dd64cc2f0ccfb1193ae0e64fadd8121dfa054bc5/packages/devtools/src/ganache/server.ts#L180). We could look at increasing the timeout as it's currently 5 seconds.

**Comment by andrewgordstewart** [comment]
These seem like two different issues (they are in different packages)

**Comment by kerzhner** [comment]
> This failure looks like it's due to `server.ready` timing out [here](https://github.com/statechannels/monorepo/blob/dd64cc2f0ccfb1193ae0e64fadd8121dfa054bc5/packages/devtools/src/ganache/server.ts#L180). We could look at increasing the timeout as it's currently 5 seconds.

Let's do it!
