### ISSUE TITLE
Nitro Protocol test failure due to timeout

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#2182]
> Another failure https://app.circleci.com/pipelines/github/statechannels/monorepo/7412/workflows/e114e689-14b3-4b7e-a5c5-fbd26ee30060/jobs/34522:
> 
> ```
> @statechannels/nitro-protocol: Error: timeout
> @statechannels/nitro-protocol:     at Timeout.timeoutFunc (/home/circleci/project/node_modules/tcp-port-used/index.js:204:25)
>  
> @statechannels/nitro-protocol:     at ontimeout (timers.js:436:11)
> @statechannels/nitro-protocol:     at tryOnTimeout (timers.js:300:5)
> @statechannels/nitro-protocol:     at listOnTimeout (timers.js:263:5)
> @statechannels/nitro-protocol:     at Timer.processTimers (timers.js:223:10)
> @statechannels/nitro-protocol: error Command failed with exit code 1.
> ```

This failure looks like it's due to `server.ready` timing out [here](https://github.com/statechannels/monorepo/blob/dd64cc2f0ccfb1193ae0e64fadd8121dfa054bc5/packages/devtools/src/ganache/server.ts#L180). We could look at increasing the timeout as it's currently 5 seconds.

_Originally posted by @lalexgap in https://github.com/statechannels/monorepo/issues/2178#issuecomment-644285266_

**Comment by andrewgordstewart** [comment]
The [test stats](https://34522-209829093-gh.circle-artifacts.com/0/test-stats) might shine some light, thought a cursory look indicates that the server was started around `72` seconds, and the test failed around `75` seconds (maybe tthe server was noto yet ready).
