### ISSUE TITLE
Uncaught (in promise) Error: No selected destination

### ISSUE THREAD

**Issue by tomclose** [statechannels/monorepo#2193]
On chrome, after clearing localStorage and IndexedDB, I consistently get stuck on "Preparing Download"

![Screen Shot 2020-06-16 at 11 43 15 AM](https://user-images.githubusercontent.com/29596/84765125-b1d2f780-afc6-11ea-9aab-aa38352d9eff.png)

[logs](https://github.com/statechannels/monorepo/files/4786078/web3torrent.Tue.16.Jun.2020.10_42_52.GMT.e623ecd2b.0x9dC44c76de7443EDB59220AC068dc3C12997f218.pino.log)

The error in the console is 
```
Uncaught (in promise) Error: No selected destination
```

**Comment by tomclose** [comment]
I managed to get it to work by disconnecting Metamask and then re-enabling.

Hypothesis: `selectedAddress` is now set at the point you enable metamask. If you enabled metamask before this point, it isn't set, and you get an error.

**Comment by lalexgap** [comment]
This may have been fixed by https://github.com/statechannels/monorepo/pull/2192. I don't think those changes have been pushed to `deploy` yet.

**Comment by lalexgap** [comment]
Confirmed fixed by #2192.
