### ISSUE TITLE
[xstate-wallet] Clicking cancel on withdraw modal leads to a freeze

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#2200]
Repro: 

- Click Withdraw in web3torrent. 
- Click cancel in the wallet. 
- return to web3torrent.
- click withdraw again
- click withdraw in the wallet. 

[web3torrent.Tue, 16 Jun 2020 16_43_43 GMT.7232f8410.0xDfA888A30F932aa6C6A8FCFc8C54D0F35584203b.pino.log](https://github.com/statechannels/monorepo/files/4787948/web3torrent.Tue.16.Jun.2020.16_43_43.GMT.7232f8410.0xDfA888A30F932aa6C6A8FCFc8C54D0F35584203b.pino.log)
![Screenshot 2020-06-16 at 17 43 54](https://user-images.githubusercontent.com/1833419/84803228-a0efa980-aff9-11ea-875d-a96c9778680e.png)
![Screenshot 2020-06-16 at 17 44 03](https://user-images.githubusercontent.com/1833419/84803219-9df4b900-aff9-11ea-8562-276235f48505.png)

**Comment by lalexgap** [comment]
I think this should be fixed by #2207

**Comment by geoknee** [comment]
Seems like it is 👍
