### ISSUE TITLE
Canceling with multiple seeders doesn't work

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#2205]
Repro steps:
1. Run multiple leecher test locally.
1. Cancel one of the leechers part way through the download.
1. Observe existing channels finish, but new channels open up.

**Comment by kerzhner** [comment]
I am currently observing the following. 
- When the leecher hits cancel, there is 1 downloading wire with a payment channel and 4 downloading wires without a payment channel.
- 1 payment channel gets closed on cancel
- for each of the other 4 a payment channel is created after cancel.

**Comment by kerzhner** [comment]
It doesn't seem like this line is ever called: https://github.com/statechannels/monorepo/blob/master/packages/web3torrent/src/library/web3torrent-lib.ts#L160

**Comment by kerzhner** [comment]
Also, doesn't seem like this line is ever called on cancel: https://github.com/statechannels/monorepo/blob/master/packages/web3torrent/src/library/web3torrent-lib.ts#L571

**Comment by kerzhner** [comment]
Take aways from today:
1. Promise returned in `closeChannel` in `payment-channel-client` never completed due to `unsubscribe` was throwing an error. I am not sure why the error is thrown. This issue is fixed in 08a438968.
1. As that promise was never completing, `torrent.destroy` was never called in `web3torrent-lib` `cancel` function.
1. Even with 08a438968, when the leecher cancels in the multiple leecher/seeder test, the cancel behavior seems broken.

**Comment by tomclose** [comment]
Here's what I think might be going on:

https://github.com/statechannels/monorepo/blob/dd64cc2f0ccfb1193ae0e64fadd8121dfa054bc5/packages/web3torrent/src/library/web3torrent-lib.ts#L158-L173

Here we use `pause` to stop the torrent. Pause prevents the torrent from connecting to new incoming or outgoing peers: 
https://github.com/webtorrent/webtorrent/blob/7ff77c3e95b2dddfa70dd49cf924073383dd565a/lib/torrent.js#L772-L776

However, it _doesn't_ stop you downloading from a peer that you're already uploading to. So you could end up opening a new channel to download from someone you already have a connection with. (Which is what I witnessed in the multiple seeder test.)

**Comment by kerzhner** [comment]
Closing in favor of https://github.com/statechannels/monorepo/issues/2227
