### ISSUE TITLE
[web3torrent] Channels stuck as starting

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#2251]
1. In production, navigate to https://web3torrent.statechannels.org/file/0ab7ca2523f6838a915f30d17ec1703b786c9e5d?name=nitro-protocol.pdf&length=403507
1. Leech the file.
<img width="1279" alt="Screen Shot 2020-06-22 at 3 28 52 PM" src="https://user-images.githubusercontent.com/1062379/85341471-1f869400-b49d-11ea-92cc-79056efe93bf.png">

[web3torrent.Mon, 22 Jun 2020 22_25_45 GMT.e865c22ae.0x127210299D9F18054fAA83ed76d7c1e79cb43F5F.pino.log](https://github.com/statechannels/monorepo/files/4815865/web3torrent.Mon.22.Jun.2020.22_25_45.GMT.e865c22ae.0x127210299D9F18054fAA83ed76d7c1e79cb43F5F.pino.log)

**Comment by kerzhner** [comment]
The starting peer is 0x74c74c3e60a3b6b88162c94053b23f2c2becde06

**Comment by geoknee** [comment]
Just to add that this blocks the user from withdrawing :-(
