### ISSUE TITLE
[wallet] Update the force-move transaction to work with new contracts

### ISSUE THREAD

**Issue by tomclose** [statechannels/monorepo#23]
We need to update the force-move transaction to work with the new contracts. 

It seems like this should only involve changes to the following piece of code: https://github.com/magmo/apps/blob/master/packages/wallet/src/redux/protocols/dispute/challenger/reducer.ts#L203-L208
```ts
  const [penultimateCommitment, lastCommitment] = channelState.commitments;
  const { commitment: fromPosition, signature: fromSignature } = penultimateCommitment;
  const { commitment: toPosition, signature: toSignature } = lastCommitment;
  const transactionRequest = createForceMoveTransaction(
    fromPosition,
    toPosition,
    fromSignature,
    toSignature,
  );
```
As far as I can see, there should be enough information in both the `channelState` and `adjudicator-state` to formulate the complete force-move transaction. You'll probably have to do some work to convert commitments into signed states etc.

**Comment by cf19drofxots** [comment]
@tomclose this commit sufficiently covers this task, right?

https://github.com/magmo/apps/commit/8555a4c6c5ce113ab1477f8ad0d3797e3746eaf2
