### ISSUE TITLE
[web3torrent] User feedback for completed downloads 

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/monorepo#244]
![image](https://user-images.githubusercontent.com/118913/67309497-58b3d200-f4d2-11e9-8f11-be42dce5a4f8.png)

When a download is completed, we're showing the following text in the Download screen:

```
Done. 0 B/s down, 0 B/s up.
Connected to 1 peers.
```

Should we provide more useful information or simply get rid of the entire message?

**Comment by spersico** [comment]
this is related to #245, and that needs to be discussed and agreed upon, before tackling this

**Comment by joelalejandro** [comment]
We're gonna support the behavior described in #245, so this issue is closed.
