### ISSUE TITLE
[web3torrent] Make the logo an SVG

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/monorepo#261]
The current logo for Web3Torrent lacks resolution. We should use an SVG file.

![image](https://user-images.githubusercontent.com/118913/67507415-38684c80-f665-11e9-8775-5c2d01fb4184.png)

**Comment by spersico** [comment]
Assets to use:
Banner: https://drive.google.com/open?id=15amJoEuYao3boOPr_zQHcovii-bshLO5
Logo: https://drive.google.com/open?id=1N_ETYmFMF5oFi8XPHyA3rVRImhAJB2hI
