### ISSUE TITLE
[web3torrent] Auto-start the upload as soon as a file has been selected

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/monorepo#263]
Instead of having to click an _Upload_ button to being the process, we can trigger the upload action as soon we've selected a file.

**Comment by spersico** [comment]
this was closed in #281. Take a look to see if this is ok:
https://drive.google.com/open?id=1xRfjW9yvJIC9fbjVXlTlmoEIcOeOd1Lx

**Comment by joelalejandro** [comment]
Excellent, marking as done.
