### ISSUE TITLE
[wallet] Update deposit to work with the new contracts

### ISSUE THREAD

**Issue by tomclose** [statechannels/monorepo#27]
As per #23 but for `deposit`. Note that this will require depositing into an asset holder, instead of the adjudicator.

### Scope
For the time being, assume that all balances are ETH balances and deposit into the ETHAssetHolder

**Comment by cf19drofxots** [comment]
Similar to the commit for #23, does the following commit suffice for this task?

https://github.com/magmo/apps/commit/6daf7b7b126321e3eaac6ba6afe83f0d2b93535e

**Comment by snario** [comment]
The wallet is currently depositing into `ETHAssetHolder`.
