### ISSUE TITLE
[wallet] Update withdraw to work with the new contracts

### ISSUE THREAD

**Issue by tomclose** [statechannels/monorepo#28]
We need to update withdraw to work with the new contracts. This is a little bit more involved than e.g. `deposit`, as the pattern of method calls have changed.

Withdraw should only apply when:
1. The channel is finalized on-chain, and
2. There are funds held in the asset holder for the channel.

In order to withdraw the participant must:

1. Call `pushOutcome`
2. Call `transferAll`

**Comment by lalexgap** [comment]
I think we want to replace `conludeAndWithdraw` with `concludePushOutcomeAndTransferAll` that @geoknee has implemented here #252

**Comment by snario** [comment]
Something I noticed is that `concludePushOutcomeAndTransferAll` does not really offer a `withdrawalAmount` parameter. How should that be handled?

**Comment by lalexgap** [comment]
> Something I noticed is that `concludePushOutcomeAndTransferAll` does not really offer a `withdrawalAmount` parameter. How should that be handled?

I think we want to remove `withdrawalAmount` from our protocols. Currently our protocols only allow for a complete withdrawal anyways, so the `withdrawalAmount` we pass in is always the player's balance in the channel.

We can implement a `PartialWithdrawal` protocol later on down the road.
