### ISSUE TITLE
[embedded-wallet] Budget Allocation screen information restructuring

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/monorepo#304]
>I think the distinction between the "statechannels.com wants to allocate" and "Recommended amount: 0.2 ETH of your send" is a bit confusing. The key operator variable here are:
>
>1. Who is asking for an allotment (statechannels.com)
>2. An allotment of what (your Send Bandwidth or your Receive Bandwidth or BOTH (most likely))
>3. How much for each Bandwidth type
>
>We also probably want some kind of FAQ page, or maybe a tooltip to explain what the heck "bandwidth" is because I bet no one will have a clue on first glance.

_Originally posted by @snario in https://github.com/statechannels/monorepo/issues/286#issuecomment-547124911_

**Comment by geoknee** [comment]
I think "budget" is a term that does justice to this concept, and agree that we may want to avoid "bandwith" which is a more technical term with many different meanings in different contexts (the main one being tied to data transmission rates, which is *not* the intended meaning here). 

That's for the "send" side of things, anyway. The more difficult concept is the 'receiving' side: but I think "receiving budget" is about as clear as you can get without going to a tooltip or FAQ page.

In summary I think "Spending budget" / "Receiving budget" works. 

A tooltip might read: _"You will not be able to send more ETH than your spending budget or receive more ETH than your receiving budget across all channels managed in this tab -- increasing either budget constitutes an increase in the level of trust you are placing in this website. A malicious page might drain your spending budget or max-out your receiving budget, requiring you to re-administer your connection with the hub on chain."_

**Comment by joelalejandro** [comment]
@snario @geoknee Can we have a rough sketch of how the modal would look with these changes?
