### ISSUE TITLE
Decouple UI interactions from engine package

### ISSUE THREAD

**Issue by cf19drofxots** [statechannels/monorepo#320]
This issue will act as an epic to track the work going into splitting up to the current tight coupling of the engine code with the UI interaction.

More concretely, this means refactoring the current implementation to not be using the `PureComponent` elements from `react`.

The following `PureComponents` are being used right now as the bridge between the `engine` and the UI. **Since this is not a small change, to prevent major divergence from master, the path of action is to keep the build and tests passing at all times while incrementally refactoring each of the following components separately** (note that the order of presentation isn't necessarily the order in which the items will be checked off; the order will be decided by whatever is easiest to refactor moving forward as this is a spike). It will likely be the case that each component will be tackled in a separate, stacked PR to make reviews easier.

The relevant PR for each protocol will be tagged to it in the following list:

- [ ] defunding
- [ ] concluding
- [ ] funding
- [ ] dispute/challenger
- [ ] dispute/challenger/components/wait-for-response-or-timeout
- [ ] dispute/responder
- [ ] dispute/responder/components/wait-for-approval
- [ ] funding-strategy-negotiation/player-a
- [ ] funding-strategy-negotiation/player-b
- [ ] ledger-funding
- [ ] ledger-defunding
- [ ] virtual-defunding
- [ ] close-ledger-channel
- [ ] withdrawing
- [ ] new-ledger-channel
- [ ] existing-ledger-funding
- [ ] consensus-update
- [ ] advance-channel
- [ ] withdrawing/components/wait-for-approval
- [ ] ledger-top-up
- [ ] new-ledger-channel/components/funding-step
- [ ] advance-channel/components/advancing-channel
- [ ] direct-funding
- [ ] direct-funding/components/funding-step
- [ ] src/containers/engine

**Comment by snario** [comment]
What's the status on this issue?

**Comment by cf19drofxots** [comment]
On pause

**Comment by lalexgap** [comment]
Refers to the old `wallet`
