### ISSUE TITLE
[web3torrent] Spike a balance-based payment model

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/monorepo#325]
Expands from #264.

The purpose of this issue is to spike a balance-based payment model.

In this model, the leecher pays a given amount of ETH, worth an amount X of data of the file. Once the balance is depleted, the leecher must pay again to continue.

- [ ] Define the minimum price a user can pay (in order to obtain a single, full piece)
- [ ] Connect to callbacks that monitor how much money remains in the balance to determine whether to keep sending or not

**Comment by andrewgordstewart** [comment]
I've written some clarification over [here](https://github.com/statechannels/monorepo/issues/264).

Here's a possible payment/choking algorithm for a balance-based model.

### Paying
p1) Bob sends some ether along with a `request` message
p2) When he doesn't receive the requested chunk, ???.
p3) When he receives the requested chunk, he requests another chunk from the same peer.

### Choking
c1) Alice unchokes the four peers that currently have the highest pay-rate with her.
c4) When she sends a `choked` message, she returns any unused funds.

**Comment by junjizhi** [comment]
@spersico Any more update on this issue? Can we move this issue to done in web3torrent project board?

**Comment by spersico** [comment]
Yeah, I'll close this. This is what we are using now.
