### ISSUE TITLE
[web3torrent] Implement Storybook

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/monorepo#357]
This issue proposes the usage of [Storybook](https://storybook.js.org) to better visualize the UI components we have on Web3Torrent.

### Components

- [x] FormButton (#359)
- [x] Spinner (#363)
- [x] ShareFile (#379)
- [x] DownloadInfo (#381)
- [x] ProgressBar (#382)
- [x] DownloadLink (#383)
- [x] MagnetLinkButton (#392)
- [x] UploadInfo (#393)

**Comment by geoknee** [comment]
Could we also please have 

- [ ] Update readme to explain storybook usage 

even if it is just a link to a storybook tutorial.

**Comment by joelalejandro** [comment]
Sure thing!
