### ISSUE TITLE
[wallet] Implement getAddress API Call

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#434]
See https://app-wallet-interface.netlify.com/ for details of the call.

The wallet should accept a `JSON-RPC` getAddress call over `postMessage` and post a JSON-RPC result back with the address.

For the initial implementation we will only generate one address/privateKey that is used across all domains.

This will be similar to how we handle `INITIALIZE_REQUEST` currently.

**Comment by snario** [comment]
I do not see `getAddress` on https://app-wallet-interface.netlify.com/

**Comment by lalexgap** [comment]
> I do not see `getAddress` on https://app-wallet-interface.netlify.com/

Hmm it looks like the latest API changes haven't been deployed (https://github.com/statechannels/monorepo/pull/427) to netlify
