### ISSUE TITLE
Enable nitro-adjudicator test

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#501]
The skip here was to unblock the remainder of the work. This needs to be un-skipped and the error it's raising is
```
VM Exception while processing transaction: revert Only the NitroAdjudicator is authorized
```

(Second comment [here](https://github.com/statechannels/monorepo/pull/424#discussion_r347055786))

_Originally posted by @cf19drofxots in https://github.com/statechannels/monorepo/pull/424_

**Comment by geoknee** [comment]
AFAIK no tests are being skipped at the present time.
