### ISSUE TITLE
[nitro-protocol | rps] Remove circular dependency in ganage/deployer

### ISSUE THREAD

**Issue by Alonski** [statechannels/monorepo#503]
Currently, there is a circular dependency in `nitro-protocol` and `RPS`.
`RPS` depends on nitro-protocol.
`nitro-protocol/ganache/deployer.ts` depends on RPS contracts.

This causes problems during build time as `nitro-protocol` is build/linted/ran before RPS.

The fix is to move the `ganache/` functionality into a different package

**Comment by lalexgap** [comment]
Currently `nitro-protocol/ganache/**` (which I will refer to as `contract-deployer`) is responsible for deploying contracts across all projects to a single ganache instance.

The `contract-deployer` currently depends on built contracts from `nitro-protocol` and `rps`.  However to start `rps` we need a started ganache instance with the `rps` and `nitro-protocol` contracts deployed.

This creates a kind of circular dependency where `contract-deployer` depends on `rps` building the contracts and `rps` depends on `contract-deployer` to deploy the contracts. This would not get solved by moving `contract-deployer` to it's own package.

One possible solution suggested by @andrewgordstewart is separating out the `rps` contracts into  a separate package.  (And possible `nitro-protocol` contracts, if the `contract-deployer` is needed by `nitro-protcol` to run contract tests?)
