### ISSUE TITLE
[hub] Clean up imports

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#522]
In many instance, the hub reaches deep into another package to import a module. For example:
`import {signState} from '@statechannels/nitro-protocol/lib/src/signatures'` in `src/hub/handlers/__test__/handle-ongoing-process-action.test.ts`.

The hub should rely on functionality that is explicitly exported by a dependency.

**Comment by snario** [comment]
Similar to https://github.com/statechannels/monorepo/issues/464

**Comment by andrewgordstewart** [comment]
We can currently enforce this with `no-submodule-imports`.

There is no eslint rule, but there is a more general `no-restricted-imports` rule that can be like
```
  'no-restricted-imports': ['error', { patterns: ['@statechannels/nitro-protocol/*'] }],
```
