### ISSUE TITLE
[wallet] Dynamically fetch ConsensusApp bytecode from the chain on wallet start

### ISSUE THREAD

**Issue by snario** [statechannels/monorepo#524]
As of #519, the bytecode for `ConsensusApp` is loaded as a constant in `constants.ts`. It is preferable to auto-fetch this from the blockchain when the wallet first starts.

**Comment by andrewgordstewart** [comment]
It's probably safe to punt this, since I think we're just going to axe the `ConsensusApp`.

**Comment by snario** [comment]
@andrewgordstewart going to use `0x0` for `appDefinition`?

**Comment by andrewgordstewart** [comment]
I think so, in which case the wallet doesn't need to call `validTransition` (because there are no valid transitions).

There may still be value in calling a function 
```
thesebytesAreIndeedAState(bytes calldata maybeAState) public pure {
  abi.decode(state, State); 
}```
in lieu of calling `validTransition(s1, s2)`

**Comment by lalexgap** [comment]
Refers to the old `wallet`
