### ISSUE TITLE
[hub] Convert all variables to snakeCase

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#547]
There are camel_case variables that are leftovers from an older repository.

**Comment by Alonski** [comment]
Example:
![image](https://user-images.githubusercontent.com/452199/69556363-3fa8b000-0fad-11ea-882e-ef21cf4c3a4f.png)

**Comment by Alonski** [comment]
Once this is fixed the ESLint rule `camelcase` should be set to `error`
