### ISSUE TITLE
Add sort-imports linting rule

### ISSUE THREAD

**Issue by snario** [statechannels/monorepo#582]
I personally really like this rule and advocate for adding it.

https://eslint.org/docs/rules/sort-imports

**Comment by Alonski** [comment]
We are already using an import plugin and rules. Are these not enough?

**Comment by andrewgordstewart** [comment]
> We are already using an import plugin and rules. Are these not enough?

Does the plugin or rules enforce sorted imports? It doesn't appear to , to me.

**Comment by Alonski** [comment]
The plugin enforces sorted imports but differently than what TSLint had.
Try changing around imports and run `yarn lint:check` :)
For example:
```
rps/src/redux/game/__tests__/scenarios.ts
  5:1  error  `ethers/constants` import should occur before import of `../../../core`  import/order
```

**Comment by Alonski** [comment]
We can still try `sort-imports` to see if its better :)

**Comment by snario** [comment]
This rule also does not appear to be used on `packages/wallet`.
