### ISSUE TITLE
Development pain-points

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#585]
After stand-up this morning, we discussed some pain points that I found trying to develop in the mono-repo after a bit of a hiatus.

Here they are written down. Perhaps we can make issues for the pain points that we want to deal with.

- [x] I ran `yarn && yarn contract:compile` from `nitro-protocol` on master, and it failed. I needed to run `yarn` from the monorepo Misleadink .
- [x] .env.defaults is misleading
- [ ] .env.local isn't loaded by default when I run `yarn contract:compile`
- [ ] env variables weren't in .env
- [ ] I ran `yarn test` from `nitro-protocol`, and got a confusing error. The docs say you need to start ganache, so that's good
- [ ] I ran `yarn start:ganache` from `nitro-protocol`, doesn't work.
- [ ] I ran `yarn start:ganache` from monorepo root, and the tests killed the ganache server
- [ ] network-context.json is checked in, and gets changed when you start ganache
- [x] I saved a file from the devtools package, and prettier formatted my file on save. When I tried to commit that file, `yarn lint:check` failed

**Comment by Alonski** [comment]
Taken from: https://github.com/statechannels/monorepo/pull/573#issuecomment-559705782

I managed to get VSCode + ESLint + Prettier playing nicely together :)
This is my .vscode/settings.json files:

{
  "eslint.validate": ["javascript", "javascriptreact", "typescript", "typescriptreact"],
  "eslint.workingDirectories": [{"directory": "packages/rps", "changeProcessCWD": true}],
  "editor.formatOnSave": true
}
We will need to setup the eslint.workingDirectories option for each package.

I also downgraded Prettier in RPS to v1.18 so its consistent with other packages.
I also changed ESLintrc to not define Prettier rules but instead to inherit them from .pretterrc
