### ISSUE TITLE
[wallet] Remove CI=false on build:webpack for CI tests

### ISSUE THREAD

**Issue by snario** [statechannels/monorepo#65]
Because of this issue: https://github.com/ethereum/web3.js/issues/3018

We have had to add `CI=false` to the `build:webpack` command here:

https://github.com/statechannels/monorepo/blob/703ae63b35878bb1e89b0fd767cc0cd6c0328318/packages/wallet/package.json#L16

When that issue is resolved, we should remove it.

**Comment by lalexgap** [comment]
Refers to the old `wallet`
