### ISSUE TITLE
Extract `FakeChannelClient` and test

### ISSUE THREAD

**Issue by tomclose** [statechannels/monorepo#688]
When building RPS, it's been really useful to be able to use the `FakeChannelClient` when developing the application. We'll probably want to provide the `FakeChannelClient` as part of the developer toolkit for state channel development. In order to do this we need to extract it and make it more robust.

This issue has two parts:

- [x] To move the `FakeChannelClient` out of `packages/rps` and into `packages/channel-client` (https://github.com/statechannels/monorepo/pull/704)
- [x] To write tests for the `FakeChannelClient` (https://github.com/statechannels/monorepo/pull/751)

For the tests for the `FakeChannelClient` it'll be useful to create a set of `ChannelResults` that correspond to a valid evolution of the channel and store these in a `scenarios` file:
```ts
const makeChannelResult = (participants, turnNum, balances, status, appDef="0x0", appData="0x0") => {....} // or whatever
const state0 = makeChannelResult([alice, bob], 0, [5, 5], 'proposed')
const state1 = makeChannelResult([alice, bob], 1, [5, 5], 'opening')
const state2 = makeChannelResult([alice, bob], 2, [5, 5], 'funded')
// etc
```
And then write tests of the form:
```ts
const clientA = new FakeChannelClient(privateKeyA) // probably useful to change interface to pass in private key
const clientB = new FakeChannelClient(privateKeyB)

const messageQueueAtoB = [];
clientA.on('MessageQueued', m => messageQueueAtoB.push(m));

const r0 = await clientA.createChannel(state0.participants, state0.balances, ...);
expect(r0).toEqual(state0);

const message0 = messageQueueAtoB.shift();
clientB.pushMessage(message0);

// need to check that clientB triggers the 'ChannelUpdated' event with state0, so will need to bind a queue to that event or similar ...
// etc.

```

**Comment by cf19drofxots** [comment]
Is there a specific entry point for how a `FakeChannelClient` could be used in the testing of web3 torrent?
