### ISSUE TITLE
[rps] Get Metamask locked error when using firefox

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#718]
When using firefox I always get this error when loading RPS. Things seem to work on  chrome.

```
Metamask Error

Your metamask account is currently locked. Please unlock it to continue.
```

**Comment by snario** [comment]
As a side note, if we fix this, can we test for it with puppeteer

**Comment by lalexgap** [comment]
> As a side note, if we fix this, can we test for it with puppeteer

I don't think so. `puppeteer` is based on starting up `chromium` instances so I don't think we can start up `firefox` with `puppeteer`

**Comment by geoknee** [comment]
I think this is probably not a firefox issue. Your chrome metamask has probably remembered that you authorised `localhost` in the past. I repro-ed the issue by removing `localhost` from my connections in metamask in chrome.
