### ISSUE TITLE
[build] Integration Tests occasionally timeout

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#721]
It seems that the integration tests occasionally timeout. Rerunning them on CircleCI will get them to pass but this is very annoying.

**Comment by snario** [comment]
We could make the integration task have some huge timeout, and the jest test as well, and then record how long these tests take into some file and then in a couple weeks review the average numbers

**Comment by lalexgap** [comment]
> We could make the integration task have some huge timeout, and the jest test as well, and then record how long these tests take into some file and then in a couple weeks review the average numbers

That's a good idea, if the failure is just caused by the tests not completing in time.

I suspect there might be a race condition somewhere though(I think the wallet might not get loaded in time for the first API call), so it may be that the when the tests fail they will timeout no matter the time we give them.
