### ISSUE TITLE
[monorepo] Use the same Prettier rules for all repos?

### ISSUE THREAD

**Issue by Alonski** [statechannels/monorepo#730]
Currently, we define root level Prettier options for the whole monorepo as well as defining different Prettier options for various packages that override the root options.

As, we are working in a monorepo maybe we should consolidate the options into the root config use those same options across all packages?

This is the root config:
```js
module.exports = {
  printWidth: 100,
  singleQuote: true,
  tabWidth: 2,
  overrides: [
    {
      files: '*.sol',
      options: {
        tabWidth: 4
      }
    }
  ]
};
```
Some changes that other packages make:
```js
// Wallet
module.exports = {
  ...require("../../.prettierrc.js"),
  singleQuote: false,
  bracketSpacing: false
};
```

```js
// Nitro Protocol
module.exports = {
  ...require('../../.prettierrc.js'),
  trailingComma: 'es5',
};
```

A few others also specify `bracketSpacing: false`.

Any thoughts?

**Comment by snario** [comment]
Most packages use the same rules and there are only a few exceptions which we can fix one at a time as needed.
