### ISSUE TITLE
[hub] Remove dependency on wallet

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#735]
Modules and types shared between the wallet and the hub are good candidates for being factored out into a separate package.

**Comment by snario** [comment]
Here are all occurrences:

https://github.com/search?utf8=%E2%9C%93&q=statechannels%2Fwallet+extension%3Ats+path%3Apackages%2Fhub&type=Code&ref=advsearch&l=&l=

**Comment by kerzhner** [comment]
@liam The search query is a bit to opportunistic
<img width="783" alt="Screen Shot 2019-12-11 at 7 37 59 AM" src="https://user-images.githubusercontent.com/1062379/70635709-3cd2cf80-1be9-11ea-9244-42624489d764.png">

**Comment by liam** [comment]
Hello,

I think you included me by mistake.
The biggest problemv here is that Ethereum doesn't scale 😉

Liam
