### ISSUE TITLE
[wallet] Race Condition in Virtual Funding in the `Wallet`

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#748]
It looks like if player A submits their transaction first and gets far enough ahead of player b in the funding protocol. It will send player B a message before player B is ready to receive the message, which causes the message to get discarded.

Both player A and player B will get stuck waiting for a post fund setup (since B discarded the message and A is waiting on B)

**Comment by kerzhner** [comment]
@lalexgap was this fixed with https://github.com/statechannels/monorepo/pull/753?

**Comment by lalexgap** [comment]
> @lalexgap was this fixed with #753?

Yup, closing
