### ISSUE TITLE
Automated script for local testing

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#757]
The script would open 2 browser windows (or use 2 existing browser windows), load RPS, and navigate through virtual funding and then through conclusion.

**Comment by kerzhner** [comment]
@andrewgordstewart If I remember correctly, you mentioning that we used to have an AppleScript executable for this.

**Comment by geoknee** [comment]
I think the work in #802 offers a solution to this. @kerzhner you could re-open this issue if it does not satisfactorily do so.

**Comment by andrewgordstewart** [comment]
I recorded a script with the Script Editor app. It generated AppleScript for me. I edited the timing, and exported it as a `.app`.

I think using puppeteer or something like that would be a better solution, as mine was quite brittle. (It was hacked together as a time saver.)
