### ISSUE TITLE
[wallet] Withdrawal screen is incorrect

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#780]
Currently the `wallet` shows a withdrawal screen that grabs the user's current address from metamask. However funds are actually sent to whatever the `destination` for the user is (currently passed in when creating a channel). 

The withdrawal screen should be updated to be accurate.

Note: Are we redoing the wallet UI at any point soon? If so we can tackle this then.

**Comment by snario** [comment]
Also, the UI says "Close Channel with Hub?" regardless whether or not the channel is with a hub or some direct other counterparty that would not characterize themselves as a hub.
