### ISSUE TITLE
integration-test-with-hub flickers

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#843]
[This job](https://app.circleci.com/jobs/github/statechannels/monorepo/8344) failed, and re-running it [passed](https://app.circleci.com/jobs/github/statechannels/monorepo/8371)

**Comment by snario** [comment]
It _might_ be possible that if two `integration-test-with-hub` jobs are running simultaneously then one or both might fail as messages are shared in the same firebase database. This might not be the cause of the flickering, but it's one hypothesis to test.

**Comment by andrewgordstewart** [comment]
<img width="1422" alt="Screen Shot 2020-01-15 at 8 57 25 AM" src="https://user-images.githubusercontent.com/8432675/72448959-233b1f80-3775-11ea-9023-dd8c6f3f9e30.png">

Good catch!
