### ISSUE TITLE
Refactor Store

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#894]
Currently the `Store` that protocols and the `xstate-wallet` depend on is defined in `wallet-specs` and inherited by `xstate-wallet`. I think there should be two separate implementations of the `IStore` in `xstate-wallet` and `wallet-specs`.

Eventually the `Store` in `wallet-spec`s  will just be used just for local testing while the `Store` in `xstate-wallet` should be an actual implementation that stores things in a more permanent store.

We should refactor two existing `Store`s so they are either separate implementations of `IStore` or share a very minimal abstract class.

Also currently both `Store` implementations handle their `messagingService` slightly differently. This should be made consistent.

**Comment by andrewgordstewart** [comment]
>Also currently both Store implementations handle their messagingService slightly differently. This should be made consistent.

Another question to answer is: should the store even handle messaging at all? Or should the machines 
1. explicitly store the data through the `IStore` interface
2. explicitly send a particular message with some `MessageService` interface

**Comment by lalexgap** [comment]
> > Also currently both Store implementations handle their messagingService slightly differently. This should be made consistent.
> 
> Another question to answer is: should the store even handle messaging at all? Or should the machines
> 
> 1. explicitly store the data through the `IStore` interface
> 2. explicitly send a particular message with some `MessageService` interface

I think if it wouldn't cause too much pain it would be good to be separated out. As well as chain interface.

**Comment by andrewgordstewart** [comment]
> if it wouldn't cause too much pain it would be good to be separated out. As well as chain interface.

I think down the road we want the store to have chain information on it, as in:
1. the chain watcher watches for events
2. on such an event, the chain watcher updates the store
3. the store emits a `{ type: 'ASSET_HOLDER_UPDATED', destination: string }` event
4. the protocol queries the store for the current chain state

**Comment by tomclose** [comment]
What would you say are the advantages of doing it this way (`ChainWatcher` -> `Store` -> `Protocols`) vs. having the protocols subscribe to both the state store and the chain watcher?

**Comment by andrewgordstewart** [comment]
I think of protocols as reacting to the current knowledge about the state of the world. So, I would suggest a third options:
- An `IStore` that has a state store and a chain store
- A `ChainWatcher` that updates the chain store
- Protocols that watch for whatever changes they are interested in on the `IStore`

That's how the current `IStore` is written, except:
- there are probably too many methods on that interface
- getter and setter methods are top level: you don't call `store.chain.getHoldings`, you just call `store.getHoldings`, which delegates to its `_chain`.
