### ISSUE TITLE
Allow challenging to close a channel

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#896]
For the purposes of the demo, we will assume that the hub is friendly and always on-line, so ****we do not need the capability to challenge the hub.

Furthermore, as we're using a simple payment channel, it is never disadvantageous for either participant to immediately conclude with the latest state (unlike RPS before a reveal say, where you could lose out by concluding). Therefore, the app can adopt the strategy that if the peer blocks at any stage, just close the channel (including during the channel setup).

We therefore only need to handle the case where the conclude step is blocked. This can be handled entirely in the wallet. If the `closeAndVirtualDefund` protocol blocks for e.g. 10 secs(?), then the wallet would pop up with:

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/95c669ad-35a9-4ab7-b94a-6dbb6849a16f/Screen_Shot_2020-01-07_at_11.05.54_AM.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/95c669ad-35a9-4ab7-b94a-6dbb6849a16f/Screen_Shot_2020-01-07_at_11.05.54_AM.png)

What challenge should the wallet actually launch here? If the user is trying to close channel `C`, supported by joint channel `J`, then it seems to make sense to simultaneously challenge in both `J` and `C` :

- If the opponent is fully offline, then both these channels need to be finalized on-chain in order to defund with the hub. This is the most likely use-case.
- The only downside is if the challenge in `C` is cleared, but the challenge in `J` is not. In this case, the parties are forced to conclude `C` on-chain later, or they can't check out with the hub.
- But it is unlikely that the challenge in `C` will be cleared, due to the fact that we're challenging with a conclude:
    - If the challenger has submitted the last conclude state, the only valid move for the opponent is to respond with a second conclude state which (TODO: should, but probably doesn't) immediately close the channel
    - If the challenger has submitted a stale state, then the responder should respond with a conclude challenge from their latest state. The above argument then applies, and the channel will close when the challenge expires.

Note: if `J` is on chain, pointing to `C`, then the hub can't settle off-chain. What we probably actually want to do is allow anyone to unilaterally change the outcome, subject to a veto.

**Comment by andrewgordstewart** [comment]
There are two types of challenging:
# App challenging

If a challenge is noticed in an app channel, there should be a workflow used to deal with it. This doesn't require a "protocol" per se, but presumably it might use some protocol.

# Auxilliary challenging

If a challenge at turn `9000` is noticed in an auxiliary channel, there are two cases:
1. Some participant has a supported state that can be used to clear the challenge.
2. No participant has a supported state that can be used to clear the challenge.

In the case of 1, then that participant probably wants to just clear the challenge. That leads to one "good-actor" protocol that you might want to specify:
- in a null-app channel, if you can clear a challenge, then you do (attempt to) clear it

In the case of 2, the participants need to collectively support a state with turn number over `9000`. So, we might end up in one of two worlds
A. they need to have some agreement between each other that they somehow support a later state; or
B. they always let the channel die and then clean up

In the case of A, this should be some specified protocol. (I've described this before in a notion doc, but I still don't have access.)

In the case of B, we obviously don't need a protocol to do this.

It is **not** true that all participants know which case it is. Eg. if in an [alice, bob] channel,
- Bob calls `forceMove(9)`
- Alice's outgoing messages are not being sent
then Alice might have a supported state at turn 10, so 1 is true, but Bob cannot know it.

There are cases where participants cannot know that 1 is false.
