### ISSUE TITLE
Virtual funding

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#902]
Some thoughts re. how we get virtual funding working

Answer the following two questions
1. Do we continue to use the `funding` protocol?

The funding protocol currently implements some decision making.
- https://xstate.js.org/viz/?gist=f3b66fdd086667323ab4bcc47230f9e7

For web3torrent, we don't want that.
We want to assume virtual funding.

We could use the existing funding protocol if the application provides a couple of services:
1. the `askClient` service in the `funding` protocol
2. a `chooseHub` service in the `virtual-funding` protocol.

One downside of this is that two extra messages will go across the wire.

We probably want to start by implementing the two fully-determined protocols: `virtual-funding-as-leaf` and `virtual-funding-as-hub`
  * as leaf: https://xstate.js.org/viz/?gist=8bee766cdc78efd02a429c1082084224
  * as hub: https://xstate.js.org/viz/?gist=bbccc52e6754a4075cba21423705b040

2. Does the hub have any say in whether or not it will enable a virtually funded app channel?

Currently, the hub implicitly agrees to fund any application channel.
Should we bother adding some decision making into this?

3. Write some tests that pass.

Here's a starter if we want to avoid using the `'funding'` protocol to do virtual funding.

https://github.com/statechannels/monorepo/tree/virtual-funding

**Comment by tomclose** [comment]
For web3torrent, the plan is to avoid these decisions, by baking in the following simplifications:

1. There is only one hub allowed: the hub run by the web3torrent app, which will be deployed at something like `hub.web3torrent.org`.
2. The app will only open virtual channels through this hub. If there is insufficient capacity on either side, channel opening will fail, and will not fall back to alternative methods.
3. The hub will always open a virtual channel, provided there is sufficient capacity on each end. (This is probably how it should work anyway - the decision phase for the hub is in whether to open a ledger channel with a user or not.)

In terms of how this is implemented in the wallet, something like this should work:

1. When the user makes the `approveBudgetAndFund` call, they provide the hub address.
2. This puts the wallet into "hub only" mode, for this domain.
3. When calling `createChannel`, the wallet checks to see which mode it is in, and then runs the `virtual-funding-as-leaf` protocol.

**Comment by andrewgordstewart** [comment]
> 2. This puts the wallet into "hub only" mode, for this domain.

The main question is how do you do this? The issue description describes the following two ways to do it:
- You can do this by letting `approveBudgetAndFund` supply the decision-making services for the channel, and those services deterministically choose virtual funding and a hard-coded hub address. 
- You can do this by storing the decisions somewhere in the wallet (the "hub only" mode), then writing a new protocol that skips the decision making steps

**Comment by lalexgap** [comment]
Out of date
