### ISSUE TITLE
Enhance client-api-schema package

### ISSUE THREAD

**Issue by tomclose** [statechannels/monorepo#957]
The client-api-schema package currently exports a bunch of types that are automatically generated from the json-schema spec. This package is not as useful as it could be because:

1. Many of the types are a bit messed up
2. Consumers have to do all the manipulation of these types themselves

It would be nice if the package exported some utility functions for working with JSON-RPC messages. For example, I want to do something like:
```ts
function handleMessage(message: any) {
	// throws an error if doesn't validate against schema
	const parsedMessage = parseMessage(message);

	switch(parsedMessage.messageType) {
		case 'request':
			// here we are a SCRequest
			switch(parsedMessage.method) {
				case 'GetAddress':
					// GetAddressRequest
				case 'UpdateChannel':
					// UpdateChannelRequest
				// ... etc.
			}
		case 'response':
		case 'notification':

		default:
			// must be one of above
			unreachable(parsedMessage);


	}
```
In particular, we want an `RPCMessage` type, that can be split via a discriminated union into one of the types of message defined in the schema. We want a `parseMessage` function that will both check the message validity, throwing an error if there's a problem, and then return an `RPCMessage` object.

To accomplish this, we might need to do some manual enhancement of the automatically-generated types, along with being more selective about what is exported. As a brief example of the current issues, here is the `Request` type currently exported by the package:
```ts
export declare type Request = {
    [k: string]: any;
} & {
    [k: string]: any;
} & {
    [k: string]: any;
} & {
    [k: string]: any;
} & {
    [k: string]: any;
} & {
    [k: string]: any;
} & {
    [k: string]: any;
};
//# sourceMappingURL=request.d.ts.map
```

I have already made a start on some of the work required on this branch: https://github.com/statechannels/monorepo/tree/client-api-changes. In particular, I have:

* Set the package up to compile and export code, instead of just types.
* Started being more selective about the types that are exported.

**Comment by lalexgap** [comment]
I think the library (`json-schema-to-typescript`) we're using to convert the json schema to typescript interfaces can't handle some of the more advance features of json schema like conditional statements, which causes strange interfaces to be generated.

It might be worth investigating if we can just convert our typescript interfaces to json schema using something like https://github.com/vega/ts-json-schema-generator.

**Comment by geoknee** [comment]
The duplicates in the schema give rise to things like

```
export type Participants = Participant[];
export type Participants1 = Participant[];
```
in `create-channel.d.ts`.

**Comment by geoknee** [comment]
And 

```typescript
/**
 * This interface was referenced by `ChannelResult`'s JSON-Schema
 * via the `definition` "ChannelStatus".
 */

export interface ChannelResult {
  [k: string]: any;
}
/**
 * This interface was referenced by `ChannelResult`'s JSON-Schema
 * via the `definition` "ChannelResult".
 */
export interface ChannelResult1 {
  participants: Participants;
  funding: {
    [k: string]: any;
  }[];
  allocations: Allocations;
  appDefinition: AppDefinition;
  appData: AppData;
  status: ChannelStatus;
  challengeExpirationTime?: ChallengeExpirationTime;
  turnNum: number;
  [k: string]: any;
}
```

in `channel-result.d.ts`
