### ISSUE TITLE
Errors in *all* environments go to sentry

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#983]
I think that's a fair point @kerzhner. Happy to fix it so that errors in *all* environments go to sentry, but with enough context so that sentry can filter out everything but production / staging errors when notifying us via slack or email.

_Originally posted by @geoknee in https://github.com/statechannels/monorepo/pull/973#issuecomment-583012902_

**Comment by snario** [comment]
@junjizhi is adding to `web3torrent` (see https://github.com/statechannels/monorepo/pull/1747)

**Comment by geoknee** [comment]
@snario Let's check this works and then close this issue?

**Comment by snario** [comment]
See #1825
